[versions]
junit = "6.1.0"
checkstyle = "13.4.2"
errorprone = "2.49.0"
errorprone-plugin = "4.2.0"
nullaway = "0.13.4"
pmd = "7.24.0"
spotbugs-tool = "4.9.8"
spotbugs-plugin = "6.4.8"
spotless = "8.5.1"
vanniktech-publish = "0.36.0"
version-catalog-update = "1.1.0"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }

[plugins]
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
vanniktech-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-publish" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
