// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct sb_parameters {
 *     int q_index;
 *     int rdmult;
 * } sb_params
 * }
 */
public class sb_params extends sb_parameters {

    sb_params() {
        // Should not be called directly
    }
}

