// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vp8_postproc_cfg {
 *     int post_proc_flag;
 *     int deblocking_level;
 *     int noise_level;
 * }
 * }
 */
public class vp8_postproc_cfg {

    vp8_postproc_cfg() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_INT.withName("post_proc_flag"),
        VpxFFI.C_INT.withName("deblocking_level"),
        VpxFFI.C_INT.withName("noise_level")
    ).withName("vp8_postproc_cfg");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt post_proc_flag$LAYOUT = (OfInt)$LAYOUT.select(groupElement("post_proc_flag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int post_proc_flag
     * }
     */
    public static final OfInt post_proc_flag$layout() {
        return post_proc_flag$LAYOUT;
    }

    private static final long post_proc_flag$OFFSET = $LAYOUT.byteOffset(groupElement("post_proc_flag"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int post_proc_flag
     * }
     */
    public static final long post_proc_flag$offset() {
        return post_proc_flag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int post_proc_flag
     * }
     */
    public static int post_proc_flag(MemorySegment struct) {
        return struct.get(post_proc_flag$LAYOUT, post_proc_flag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int post_proc_flag
     * }
     */
    public static void post_proc_flag(MemorySegment struct, int fieldValue) {
        struct.set(post_proc_flag$LAYOUT, post_proc_flag$OFFSET, fieldValue);
    }

    private static final OfInt deblocking_level$LAYOUT = (OfInt)$LAYOUT.select(groupElement("deblocking_level"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int deblocking_level
     * }
     */
    public static final OfInt deblocking_level$layout() {
        return deblocking_level$LAYOUT;
    }

    private static final long deblocking_level$OFFSET = $LAYOUT.byteOffset(groupElement("deblocking_level"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int deblocking_level
     * }
     */
    public static final long deblocking_level$offset() {
        return deblocking_level$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int deblocking_level
     * }
     */
    public static int deblocking_level(MemorySegment struct) {
        return struct.get(deblocking_level$LAYOUT, deblocking_level$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int deblocking_level
     * }
     */
    public static void deblocking_level(MemorySegment struct, int fieldValue) {
        struct.set(deblocking_level$LAYOUT, deblocking_level$OFFSET, fieldValue);
    }

    private static final OfInt noise_level$LAYOUT = (OfInt)$LAYOUT.select(groupElement("noise_level"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int noise_level
     * }
     */
    public static final OfInt noise_level$layout() {
        return noise_level$LAYOUT;
    }

    private static final long noise_level$OFFSET = $LAYOUT.byteOffset(groupElement("noise_level"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int noise_level
     * }
     */
    public static final long noise_level$offset() {
        return noise_level$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int noise_level
     * }
     */
    public static int noise_level(MemorySegment struct) {
        return struct.get(noise_level$LAYOUT, noise_level$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int noise_level
     * }
     */
    public static void noise_level(MemorySegment struct, int fieldValue) {
        struct.set(noise_level$LAYOUT, noise_level$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

