// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vp8_postproc_cfg {
 *     int post_proc_flag;
 *     int deblocking_level;
 *     int noise_level;
 * } vp8_postproc_cfg_t
 * }
 */
public class vp8_postproc_cfg_t extends vp8_postproc_cfg {

    vp8_postproc_cfg_t() {
        // Should not be called directly
    }
}

