// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vp9_ref_frame {
 *     int idx;
 *     vpx_image_t img;
 * }
 * }
 */
public class vp9_ref_frame {

    vp9_ref_frame() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_INT.withName("idx"),
        MemoryLayout.paddingLayout(4),
        vpx_image.layout().withName("img")
    ).withName("vp9_ref_frame");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt idx$LAYOUT = (OfInt)$LAYOUT.select(groupElement("idx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int idx
     * }
     */
    public static final OfInt idx$layout() {
        return idx$LAYOUT;
    }

    private static final long idx$OFFSET = $LAYOUT.byteOffset(groupElement("idx"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int idx
     * }
     */
    public static final long idx$offset() {
        return idx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int idx
     * }
     */
    public static int idx(MemorySegment struct) {
        return struct.get(idx$LAYOUT, idx$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int idx
     * }
     */
    public static void idx(MemorySegment struct, int fieldValue) {
        struct.set(idx$LAYOUT, idx$OFFSET, fieldValue);
    }

    private static final GroupLayout img$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("img"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_image_t img
     * }
     */
    public static final GroupLayout img$layout() {
        return img$LAYOUT;
    }

    private static final long img$OFFSET = $LAYOUT.byteOffset(groupElement("img"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_image_t img
     * }
     */
    public static final long img$offset() {
        return img$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_image_t img
     * }
     */
    public static MemorySegment img(MemorySegment struct) {
        return struct.asSlice(img$OFFSET, img$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_image_t img
     * }
     */
    public static void img(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, img$OFFSET, img$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

