// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_svc_parameters {
 *     int max_quantizers[12];
 *     int min_quantizers[12];
 *     int scaling_factor_num[12];
 *     int scaling_factor_den[12];
 *     int speed_per_layer[12];
 *     int temporal_layering_mode;
 *     int loopfilter_ctrl[12];
 * } vpx_svc_extra_cfg_t
 * }
 */
public class vpx_svc_extra_cfg_t extends vpx_svc_parameters {

    vpx_svc_extra_cfg_t() {
        // Should not be called directly
    }
}

