// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_codec_frame_buffer {
 *     uint8_t *data;
 *     size_t size;
 *     void *priv;
 * } vpx_codec_frame_buffer_t
 * }
 */
public class vpx_codec_frame_buffer_t extends vpx_codec_frame_buffer {

    vpx_codec_frame_buffer_t() {
        // Should not be called directly
    }
}

