// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_rc_encodeframe_info {
 *     int frame_type;
 *     int show_index;
 *     int coding_index;
 *     int gop_index;
 *     int ref_frame_coding_indexes[3];
 *     int ref_frame_valid_list[3];
 *     int gop_size;
 *     int use_alt_ref;
 * } vpx_rc_encodeframe_info_t
 * }
 */
public class vpx_rc_encodeframe_info_t extends vpx_rc_encodeframe_info {

    vpx_rc_encodeframe_info_t() {
        // Should not be called directly
    }
}

