// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_ref_frame {
 *     vpx_ref_frame_type_t frame_type;
 *     vpx_image_t img;
 * } vpx_ref_frame_t
 * }
 */
public class vpx_ref_frame_t extends vpx_ref_frame {

    vpx_ref_frame_t() {
        // Should not be called directly
    }
}

