// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef vpx_rc_status_t (*vpx_rc_create_model_cb_fn_t)(void *, const vpx_rc_config_t *, vpx_rc_model_t *)
 * }
 */
public final class vpx_rc_create_model_cb_fn_t {

    private vpx_rc_create_model_cb_fn_t() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment priv, MemorySegment ratectrl_config, MemorySegment rate_ctrl_model_ptr);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        VpxFFI.C_INT,
        VpxFFI.C_POINTER,
        VpxFFI.C_POINTER,
        VpxFFI.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = VpxFFI.upcallHandle(vpx_rc_create_model_cb_fn_t.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(vpx_rc_create_model_cb_fn_t.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr, MemorySegment priv, MemorySegment ratectrl_config, MemorySegment rate_ctrl_model_ptr) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, priv, ratectrl_config, rate_ctrl_model_ptr);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

