// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_svc_parameters {
 *     int max_quantizers[12];
 *     int min_quantizers[12];
 *     int scaling_factor_num[12];
 *     int scaling_factor_den[12];
 *     int speed_per_layer[12];
 *     int temporal_layering_mode;
 *     int loopfilter_ctrl[12];
 * }
 * }
 */
public class vpx_svc_parameters {

    vpx_svc_parameters() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(12, VpxFFI.C_INT).withName("max_quantizers"),
        MemoryLayout.sequenceLayout(12, VpxFFI.C_INT).withName("min_quantizers"),
        MemoryLayout.sequenceLayout(12, VpxFFI.C_INT).withName("scaling_factor_num"),
        MemoryLayout.sequenceLayout(12, VpxFFI.C_INT).withName("scaling_factor_den"),
        MemoryLayout.sequenceLayout(12, VpxFFI.C_INT).withName("speed_per_layer"),
        VpxFFI.C_INT.withName("temporal_layering_mode"),
        MemoryLayout.sequenceLayout(12, VpxFFI.C_INT).withName("loopfilter_ctrl")
    ).withName("vpx_svc_parameters");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout max_quantizers$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("max_quantizers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int max_quantizers[12]
     * }
     */
    public static final SequenceLayout max_quantizers$layout() {
        return max_quantizers$LAYOUT;
    }

    private static final long max_quantizers$OFFSET = $LAYOUT.byteOffset(groupElement("max_quantizers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int max_quantizers[12]
     * }
     */
    public static final long max_quantizers$offset() {
        return max_quantizers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int max_quantizers[12]
     * }
     */
    public static MemorySegment max_quantizers(MemorySegment struct) {
        return struct.asSlice(max_quantizers$OFFSET, max_quantizers$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int max_quantizers[12]
     * }
     */
    public static void max_quantizers(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, max_quantizers$OFFSET, max_quantizers$LAYOUT.byteSize());
    }

    private static long[] max_quantizers$DIMS = { 12 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int max_quantizers[12]
     * }
     */
    public static long[] max_quantizers$dimensions() {
        return max_quantizers$DIMS;
    }
    private static final VarHandle max_quantizers$ELEM_HANDLE = max_quantizers$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int max_quantizers[12]
     * }
     */
    public static int max_quantizers(MemorySegment struct, long index0) {
        return (int)max_quantizers$ELEM_HANDLE.get(struct, max_quantizers$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int max_quantizers[12]
     * }
     */
    public static void max_quantizers(MemorySegment struct, long index0, int fieldValue) {
        max_quantizers$ELEM_HANDLE.set(struct, max_quantizers$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout min_quantizers$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("min_quantizers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int min_quantizers[12]
     * }
     */
    public static final SequenceLayout min_quantizers$layout() {
        return min_quantizers$LAYOUT;
    }

    private static final long min_quantizers$OFFSET = $LAYOUT.byteOffset(groupElement("min_quantizers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int min_quantizers[12]
     * }
     */
    public static final long min_quantizers$offset() {
        return min_quantizers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int min_quantizers[12]
     * }
     */
    public static MemorySegment min_quantizers(MemorySegment struct) {
        return struct.asSlice(min_quantizers$OFFSET, min_quantizers$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int min_quantizers[12]
     * }
     */
    public static void min_quantizers(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, min_quantizers$OFFSET, min_quantizers$LAYOUT.byteSize());
    }

    private static long[] min_quantizers$DIMS = { 12 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int min_quantizers[12]
     * }
     */
    public static long[] min_quantizers$dimensions() {
        return min_quantizers$DIMS;
    }
    private static final VarHandle min_quantizers$ELEM_HANDLE = min_quantizers$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int min_quantizers[12]
     * }
     */
    public static int min_quantizers(MemorySegment struct, long index0) {
        return (int)min_quantizers$ELEM_HANDLE.get(struct, min_quantizers$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int min_quantizers[12]
     * }
     */
    public static void min_quantizers(MemorySegment struct, long index0, int fieldValue) {
        min_quantizers$ELEM_HANDLE.set(struct, min_quantizers$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout scaling_factor_num$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("scaling_factor_num"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int scaling_factor_num[12]
     * }
     */
    public static final SequenceLayout scaling_factor_num$layout() {
        return scaling_factor_num$LAYOUT;
    }

    private static final long scaling_factor_num$OFFSET = $LAYOUT.byteOffset(groupElement("scaling_factor_num"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int scaling_factor_num[12]
     * }
     */
    public static final long scaling_factor_num$offset() {
        return scaling_factor_num$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int scaling_factor_num[12]
     * }
     */
    public static MemorySegment scaling_factor_num(MemorySegment struct) {
        return struct.asSlice(scaling_factor_num$OFFSET, scaling_factor_num$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int scaling_factor_num[12]
     * }
     */
    public static void scaling_factor_num(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, scaling_factor_num$OFFSET, scaling_factor_num$LAYOUT.byteSize());
    }

    private static long[] scaling_factor_num$DIMS = { 12 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int scaling_factor_num[12]
     * }
     */
    public static long[] scaling_factor_num$dimensions() {
        return scaling_factor_num$DIMS;
    }
    private static final VarHandle scaling_factor_num$ELEM_HANDLE = scaling_factor_num$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int scaling_factor_num[12]
     * }
     */
    public static int scaling_factor_num(MemorySegment struct, long index0) {
        return (int)scaling_factor_num$ELEM_HANDLE.get(struct, scaling_factor_num$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int scaling_factor_num[12]
     * }
     */
    public static void scaling_factor_num(MemorySegment struct, long index0, int fieldValue) {
        scaling_factor_num$ELEM_HANDLE.set(struct, scaling_factor_num$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout scaling_factor_den$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("scaling_factor_den"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int scaling_factor_den[12]
     * }
     */
    public static final SequenceLayout scaling_factor_den$layout() {
        return scaling_factor_den$LAYOUT;
    }

    private static final long scaling_factor_den$OFFSET = $LAYOUT.byteOffset(groupElement("scaling_factor_den"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int scaling_factor_den[12]
     * }
     */
    public static final long scaling_factor_den$offset() {
        return scaling_factor_den$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int scaling_factor_den[12]
     * }
     */
    public static MemorySegment scaling_factor_den(MemorySegment struct) {
        return struct.asSlice(scaling_factor_den$OFFSET, scaling_factor_den$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int scaling_factor_den[12]
     * }
     */
    public static void scaling_factor_den(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, scaling_factor_den$OFFSET, scaling_factor_den$LAYOUT.byteSize());
    }

    private static long[] scaling_factor_den$DIMS = { 12 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int scaling_factor_den[12]
     * }
     */
    public static long[] scaling_factor_den$dimensions() {
        return scaling_factor_den$DIMS;
    }
    private static final VarHandle scaling_factor_den$ELEM_HANDLE = scaling_factor_den$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int scaling_factor_den[12]
     * }
     */
    public static int scaling_factor_den(MemorySegment struct, long index0) {
        return (int)scaling_factor_den$ELEM_HANDLE.get(struct, scaling_factor_den$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int scaling_factor_den[12]
     * }
     */
    public static void scaling_factor_den(MemorySegment struct, long index0, int fieldValue) {
        scaling_factor_den$ELEM_HANDLE.set(struct, scaling_factor_den$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout speed_per_layer$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("speed_per_layer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int speed_per_layer[12]
     * }
     */
    public static final SequenceLayout speed_per_layer$layout() {
        return speed_per_layer$LAYOUT;
    }

    private static final long speed_per_layer$OFFSET = $LAYOUT.byteOffset(groupElement("speed_per_layer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int speed_per_layer[12]
     * }
     */
    public static final long speed_per_layer$offset() {
        return speed_per_layer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int speed_per_layer[12]
     * }
     */
    public static MemorySegment speed_per_layer(MemorySegment struct) {
        return struct.asSlice(speed_per_layer$OFFSET, speed_per_layer$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int speed_per_layer[12]
     * }
     */
    public static void speed_per_layer(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, speed_per_layer$OFFSET, speed_per_layer$LAYOUT.byteSize());
    }

    private static long[] speed_per_layer$DIMS = { 12 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int speed_per_layer[12]
     * }
     */
    public static long[] speed_per_layer$dimensions() {
        return speed_per_layer$DIMS;
    }
    private static final VarHandle speed_per_layer$ELEM_HANDLE = speed_per_layer$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int speed_per_layer[12]
     * }
     */
    public static int speed_per_layer(MemorySegment struct, long index0) {
        return (int)speed_per_layer$ELEM_HANDLE.get(struct, speed_per_layer$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int speed_per_layer[12]
     * }
     */
    public static void speed_per_layer(MemorySegment struct, long index0, int fieldValue) {
        speed_per_layer$ELEM_HANDLE.set(struct, speed_per_layer$OFFSET, index0, fieldValue);
    }

    private static final OfInt temporal_layering_mode$LAYOUT = (OfInt)$LAYOUT.select(groupElement("temporal_layering_mode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int temporal_layering_mode
     * }
     */
    public static final OfInt temporal_layering_mode$layout() {
        return temporal_layering_mode$LAYOUT;
    }

    private static final long temporal_layering_mode$OFFSET = $LAYOUT.byteOffset(groupElement("temporal_layering_mode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int temporal_layering_mode
     * }
     */
    public static final long temporal_layering_mode$offset() {
        return temporal_layering_mode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int temporal_layering_mode
     * }
     */
    public static int temporal_layering_mode(MemorySegment struct) {
        return struct.get(temporal_layering_mode$LAYOUT, temporal_layering_mode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int temporal_layering_mode
     * }
     */
    public static void temporal_layering_mode(MemorySegment struct, int fieldValue) {
        struct.set(temporal_layering_mode$LAYOUT, temporal_layering_mode$OFFSET, fieldValue);
    }

    private static final SequenceLayout loopfilter_ctrl$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("loopfilter_ctrl"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int loopfilter_ctrl[12]
     * }
     */
    public static final SequenceLayout loopfilter_ctrl$layout() {
        return loopfilter_ctrl$LAYOUT;
    }

    private static final long loopfilter_ctrl$OFFSET = $LAYOUT.byteOffset(groupElement("loopfilter_ctrl"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int loopfilter_ctrl[12]
     * }
     */
    public static final long loopfilter_ctrl$offset() {
        return loopfilter_ctrl$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int loopfilter_ctrl[12]
     * }
     */
    public static MemorySegment loopfilter_ctrl(MemorySegment struct) {
        return struct.asSlice(loopfilter_ctrl$OFFSET, loopfilter_ctrl$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int loopfilter_ctrl[12]
     * }
     */
    public static void loopfilter_ctrl(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, loopfilter_ctrl$OFFSET, loopfilter_ctrl$LAYOUT.byteSize());
    }

    private static long[] loopfilter_ctrl$DIMS = { 12 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int loopfilter_ctrl[12]
     * }
     */
    public static long[] loopfilter_ctrl$dimensions() {
        return loopfilter_ctrl$DIMS;
    }
    private static final VarHandle loopfilter_ctrl$ELEM_HANDLE = loopfilter_ctrl$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int loopfilter_ctrl[12]
     * }
     */
    public static int loopfilter_ctrl(MemorySegment struct, long index0) {
        return (int)loopfilter_ctrl$ELEM_HANDLE.get(struct, loopfilter_ctrl$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int loopfilter_ctrl[12]
     * }
     */
    public static void loopfilter_ctrl(MemorySegment struct, long index0, int fieldValue) {
        loopfilter_ctrl$ELEM_HANDLE.set(struct, loopfilter_ctrl$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

