// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_active_map {
 *     unsigned char *active_map;
 *     unsigned int rows;
 *     unsigned int cols;
 * } vpx_active_map_t
 * }
 */
public class vpx_active_map_t extends vpx_active_map {

    vpx_active_map_t() {
        // Should not be called directly
    }
}

