// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_image {
 *     vpx_img_fmt_t fmt;
 *     vpx_color_space_t cs;
 *     vpx_color_range_t range;
 *     unsigned int w;
 *     unsigned int h;
 *     unsigned int bit_depth;
 *     unsigned int d_w;
 *     unsigned int d_h;
 *     unsigned int r_w;
 *     unsigned int r_h;
 *     unsigned int x_chroma_shift;
 *     unsigned int y_chroma_shift;
 *     unsigned char *planes[4];
 *     int stride[4];
 *     int bps;
 *     void *user_priv;
 *     unsigned char *img_data;
 *     int img_data_owner;
 *     int self_allocd;
 *     void *fb_priv;
 * } vpx_image_t
 * }
 */
public class vpx_image_t extends vpx_image {

    vpx_image_t() {
        // Should not be called directly
    }
}

