// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_image_rect {
 *     unsigned int x;
 *     unsigned int y;
 *     unsigned int w;
 *     unsigned int h;
 * } vpx_image_rect_t
 * }
 */
public class vpx_image_rect_t extends vpx_image_rect {

    vpx_image_rect_t() {
        // Should not be called directly
    }
}

