// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_svc_spatial_layer_sync {
 *     int spatial_layer_sync[5];
 *     int base_layer_intra_only;
 * }
 * }
 */
public class vpx_svc_spatial_layer_sync {

    vpx_svc_spatial_layer_sync() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(5, VpxFFI.C_INT).withName("spatial_layer_sync"),
        VpxFFI.C_INT.withName("base_layer_intra_only")
    ).withName("vpx_svc_spatial_layer_sync");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout spatial_layer_sync$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("spatial_layer_sync"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int spatial_layer_sync[5]
     * }
     */
    public static final SequenceLayout spatial_layer_sync$layout() {
        return spatial_layer_sync$LAYOUT;
    }

    private static final long spatial_layer_sync$OFFSET = $LAYOUT.byteOffset(groupElement("spatial_layer_sync"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int spatial_layer_sync[5]
     * }
     */
    public static final long spatial_layer_sync$offset() {
        return spatial_layer_sync$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int spatial_layer_sync[5]
     * }
     */
    public static MemorySegment spatial_layer_sync(MemorySegment struct) {
        return struct.asSlice(spatial_layer_sync$OFFSET, spatial_layer_sync$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int spatial_layer_sync[5]
     * }
     */
    public static void spatial_layer_sync(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, spatial_layer_sync$OFFSET, spatial_layer_sync$LAYOUT.byteSize());
    }

    private static long[] spatial_layer_sync$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int spatial_layer_sync[5]
     * }
     */
    public static long[] spatial_layer_sync$dimensions() {
        return spatial_layer_sync$DIMS;
    }
    private static final VarHandle spatial_layer_sync$ELEM_HANDLE = spatial_layer_sync$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int spatial_layer_sync[5]
     * }
     */
    public static int spatial_layer_sync(MemorySegment struct, long index0) {
        return (int)spatial_layer_sync$ELEM_HANDLE.get(struct, spatial_layer_sync$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int spatial_layer_sync[5]
     * }
     */
    public static void spatial_layer_sync(MemorySegment struct, long index0, int fieldValue) {
        spatial_layer_sync$ELEM_HANDLE.set(struct, spatial_layer_sync$OFFSET, index0, fieldValue);
    }

    private static final OfInt base_layer_intra_only$LAYOUT = (OfInt)$LAYOUT.select(groupElement("base_layer_intra_only"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int base_layer_intra_only
     * }
     */
    public static final OfInt base_layer_intra_only$layout() {
        return base_layer_intra_only$LAYOUT;
    }

    private static final long base_layer_intra_only$OFFSET = $LAYOUT.byteOffset(groupElement("base_layer_intra_only"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int base_layer_intra_only
     * }
     */
    public static final long base_layer_intra_only$offset() {
        return base_layer_intra_only$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int base_layer_intra_only
     * }
     */
    public static int base_layer_intra_only(MemorySegment struct) {
        return struct.get(base_layer_intra_only$LAYOUT, base_layer_intra_only$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int base_layer_intra_only
     * }
     */
    public static void base_layer_intra_only(MemorySegment struct, int fieldValue) {
        struct.set(base_layer_intra_only$LAYOUT, base_layer_intra_only$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

