// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_svc_layer_id {
 *     int spatial_layer_id;
 *     int temporal_layer_id;
 *     int temporal_layer_id_per_spatial[5];
 * }
 * }
 */
public class vpx_svc_layer_id {

    vpx_svc_layer_id() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_INT.withName("spatial_layer_id"),
        VpxFFI.C_INT.withName("temporal_layer_id"),
        MemoryLayout.sequenceLayout(5, VpxFFI.C_INT).withName("temporal_layer_id_per_spatial")
    ).withName("vpx_svc_layer_id");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt spatial_layer_id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("spatial_layer_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int spatial_layer_id
     * }
     */
    public static final OfInt spatial_layer_id$layout() {
        return spatial_layer_id$LAYOUT;
    }

    private static final long spatial_layer_id$OFFSET = $LAYOUT.byteOffset(groupElement("spatial_layer_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int spatial_layer_id
     * }
     */
    public static final long spatial_layer_id$offset() {
        return spatial_layer_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int spatial_layer_id
     * }
     */
    public static int spatial_layer_id(MemorySegment struct) {
        return struct.get(spatial_layer_id$LAYOUT, spatial_layer_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int spatial_layer_id
     * }
     */
    public static void spatial_layer_id(MemorySegment struct, int fieldValue) {
        struct.set(spatial_layer_id$LAYOUT, spatial_layer_id$OFFSET, fieldValue);
    }

    private static final OfInt temporal_layer_id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("temporal_layer_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int temporal_layer_id
     * }
     */
    public static final OfInt temporal_layer_id$layout() {
        return temporal_layer_id$LAYOUT;
    }

    private static final long temporal_layer_id$OFFSET = $LAYOUT.byteOffset(groupElement("temporal_layer_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int temporal_layer_id
     * }
     */
    public static final long temporal_layer_id$offset() {
        return temporal_layer_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int temporal_layer_id
     * }
     */
    public static int temporal_layer_id(MemorySegment struct) {
        return struct.get(temporal_layer_id$LAYOUT, temporal_layer_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int temporal_layer_id
     * }
     */
    public static void temporal_layer_id(MemorySegment struct, int fieldValue) {
        struct.set(temporal_layer_id$LAYOUT, temporal_layer_id$OFFSET, fieldValue);
    }

    private static final SequenceLayout temporal_layer_id_per_spatial$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("temporal_layer_id_per_spatial"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int temporal_layer_id_per_spatial[5]
     * }
     */
    public static final SequenceLayout temporal_layer_id_per_spatial$layout() {
        return temporal_layer_id_per_spatial$LAYOUT;
    }

    private static final long temporal_layer_id_per_spatial$OFFSET = $LAYOUT.byteOffset(groupElement("temporal_layer_id_per_spatial"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int temporal_layer_id_per_spatial[5]
     * }
     */
    public static final long temporal_layer_id_per_spatial$offset() {
        return temporal_layer_id_per_spatial$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int temporal_layer_id_per_spatial[5]
     * }
     */
    public static MemorySegment temporal_layer_id_per_spatial(MemorySegment struct) {
        return struct.asSlice(temporal_layer_id_per_spatial$OFFSET, temporal_layer_id_per_spatial$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int temporal_layer_id_per_spatial[5]
     * }
     */
    public static void temporal_layer_id_per_spatial(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, temporal_layer_id_per_spatial$OFFSET, temporal_layer_id_per_spatial$LAYOUT.byteSize());
    }

    private static long[] temporal_layer_id_per_spatial$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int temporal_layer_id_per_spatial[5]
     * }
     */
    public static long[] temporal_layer_id_per_spatial$dimensions() {
        return temporal_layer_id_per_spatial$DIMS;
    }
    private static final VarHandle temporal_layer_id_per_spatial$ELEM_HANDLE = temporal_layer_id_per_spatial$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int temporal_layer_id_per_spatial[5]
     * }
     */
    public static int temporal_layer_id_per_spatial(MemorySegment struct, long index0) {
        return (int)temporal_layer_id_per_spatial$ELEM_HANDLE.get(struct, temporal_layer_id_per_spatial$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int temporal_layer_id_per_spatial[5]
     * }
     */
    public static void temporal_layer_id_per_spatial(MemorySegment struct, long index0, int fieldValue) {
        temporal_layer_id_per_spatial$ELEM_HANDLE.set(struct, temporal_layer_id_per_spatial$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

