// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_rc_key_frame_decision {
 *     int key_frame_show_index;
 *     int key_frame_group_size;
 * } vpx_rc_key_frame_decision_t
 * }
 */
public class vpx_rc_key_frame_decision_t extends vpx_rc_key_frame_decision {

    vpx_rc_key_frame_decision_t() {
        // Should not be called directly
    }
}

