// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_scaling_mode {
 *     VPX_SCALING_MODE h_scaling_mode;
 *     VPX_SCALING_MODE v_scaling_mode;
 * } vpx_scaling_mode_t
 * }
 */
public class vpx_scaling_mode_t extends vpx_scaling_mode$0 {

    vpx_scaling_mode_t() {
        // Should not be called directly
    }
}

