// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_svc_frame_drop {
 *     int framedrop_thresh[5];
 *     SVC_LAYER_DROP_MODE framedrop_mode;
 *     int max_consec_drop;
 * } vpx_svc_frame_drop_t
 * }
 */
public class vpx_svc_frame_drop_t extends vpx_svc_frame_drop {

    vpx_svc_frame_drop_t() {
        // Should not be called directly
    }
}

