// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_codec_enc_output_cx_cb_pair {
 *     vpx_codec_enc_output_cx_pkt_cb_fn_t output_cx_pkt;
 *     void *user_priv;
 * } vpx_codec_priv_output_cx_pkt_cb_pair_t
 * }
 */
public class vpx_codec_priv_output_cx_pkt_cb_pair_t extends vpx_codec_enc_output_cx_cb_pair {

    vpx_codec_priv_output_cx_pkt_cb_pair_t() {
        // Should not be called directly
    }
}

