// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_rc_frame_stats {
 *     double frame;
 *     double weight;
 *     double intra_error;
 *     double coded_error;
 *     double sr_coded_error;
 *     double frame_noise_energy;
 *     double pcnt_inter;
 *     double pcnt_motion;
 *     double pcnt_second_ref;
 *     double pcnt_neutral;
 *     double pcnt_intra_low;
 *     double pcnt_intra_high;
 *     double intra_skip_pct;
 *     double intra_smooth_pct;
 *     double inactive_zone_rows;
 *     double inactive_zone_cols;
 *     double MVr;
 *     double mvr_abs;
 *     double MVc;
 *     double mvc_abs;
 *     double MVrv;
 *     double MVcv;
 *     double mv_in_out_count;
 *     double duration;
 *     double count;
 *     double new_mv_count;
 * } vpx_rc_frame_stats_t
 * }
 */
public class vpx_rc_frame_stats_t extends vpx_rc_frame_stats {

    vpx_rc_frame_stats_t() {
        // Should not be called directly
    }
}

