// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_rc_key_frame_decision {
 *     int key_frame_show_index;
 *     int key_frame_group_size;
 * }
 * }
 */
public class vpx_rc_key_frame_decision {

    vpx_rc_key_frame_decision() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_INT.withName("key_frame_show_index"),
        VpxFFI.C_INT.withName("key_frame_group_size")
    ).withName("vpx_rc_key_frame_decision");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt key_frame_show_index$LAYOUT = (OfInt)$LAYOUT.select(groupElement("key_frame_show_index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int key_frame_show_index
     * }
     */
    public static final OfInt key_frame_show_index$layout() {
        return key_frame_show_index$LAYOUT;
    }

    private static final long key_frame_show_index$OFFSET = $LAYOUT.byteOffset(groupElement("key_frame_show_index"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int key_frame_show_index
     * }
     */
    public static final long key_frame_show_index$offset() {
        return key_frame_show_index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int key_frame_show_index
     * }
     */
    public static int key_frame_show_index(MemorySegment struct) {
        return struct.get(key_frame_show_index$LAYOUT, key_frame_show_index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int key_frame_show_index
     * }
     */
    public static void key_frame_show_index(MemorySegment struct, int fieldValue) {
        struct.set(key_frame_show_index$LAYOUT, key_frame_show_index$OFFSET, fieldValue);
    }

    private static final OfInt key_frame_group_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("key_frame_group_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int key_frame_group_size
     * }
     */
    public static final OfInt key_frame_group_size$layout() {
        return key_frame_group_size$LAYOUT;
    }

    private static final long key_frame_group_size$OFFSET = $LAYOUT.byteOffset(groupElement("key_frame_group_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int key_frame_group_size
     * }
     */
    public static final long key_frame_group_size$offset() {
        return key_frame_group_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int key_frame_group_size
     * }
     */
    public static int key_frame_group_size(MemorySegment struct) {
        return struct.get(key_frame_group_size$LAYOUT, key_frame_group_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int key_frame_group_size
     * }
     */
    public static void key_frame_group_size(MemorySegment struct, int fieldValue) {
        struct.set(key_frame_group_size$LAYOUT, key_frame_group_size$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

