// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_roi_map {
 *     uint8_t enabled;
 *     unsigned char *roi_map;
 *     unsigned int rows;
 *     unsigned int cols;
 *     int delta_q[8];
 *     int delta_lf[8];
 *     int skip[8];
 *     int ref_frame[8];
 *     unsigned int static_threshold[4];
 * }
 * }
 */
public class vpx_roi_map {

    vpx_roi_map() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_CHAR.withName("enabled"),
        MemoryLayout.paddingLayout(7),
        VpxFFI.C_POINTER.withName("roi_map"),
        VpxFFI.C_INT.withName("rows"),
        VpxFFI.C_INT.withName("cols"),
        MemoryLayout.sequenceLayout(8, VpxFFI.C_INT).withName("delta_q"),
        MemoryLayout.sequenceLayout(8, VpxFFI.C_INT).withName("delta_lf"),
        MemoryLayout.sequenceLayout(8, VpxFFI.C_INT).withName("skip"),
        MemoryLayout.sequenceLayout(8, VpxFFI.C_INT).withName("ref_frame"),
        MemoryLayout.sequenceLayout(4, VpxFFI.C_INT).withName("static_threshold")
    ).withName("vpx_roi_map");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte enabled$LAYOUT = (OfByte)$LAYOUT.select(groupElement("enabled"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t enabled
     * }
     */
    public static final OfByte enabled$layout() {
        return enabled$LAYOUT;
    }

    private static final long enabled$OFFSET = $LAYOUT.byteOffset(groupElement("enabled"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t enabled
     * }
     */
    public static final long enabled$offset() {
        return enabled$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t enabled
     * }
     */
    public static byte enabled(MemorySegment struct) {
        return struct.get(enabled$LAYOUT, enabled$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t enabled
     * }
     */
    public static void enabled(MemorySegment struct, byte fieldValue) {
        struct.set(enabled$LAYOUT, enabled$OFFSET, fieldValue);
    }

    private static final AddressLayout roi_map$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("roi_map"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char *roi_map
     * }
     */
    public static final AddressLayout roi_map$layout() {
        return roi_map$LAYOUT;
    }

    private static final long roi_map$OFFSET = $LAYOUT.byteOffset(groupElement("roi_map"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char *roi_map
     * }
     */
    public static final long roi_map$offset() {
        return roi_map$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char *roi_map
     * }
     */
    public static MemorySegment roi_map(MemorySegment struct) {
        return struct.get(roi_map$LAYOUT, roi_map$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char *roi_map
     * }
     */
    public static void roi_map(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(roi_map$LAYOUT, roi_map$OFFSET, fieldValue);
    }

    private static final OfInt rows$LAYOUT = (OfInt)$LAYOUT.select(groupElement("rows"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int rows
     * }
     */
    public static final OfInt rows$layout() {
        return rows$LAYOUT;
    }

    private static final long rows$OFFSET = $LAYOUT.byteOffset(groupElement("rows"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int rows
     * }
     */
    public static final long rows$offset() {
        return rows$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int rows
     * }
     */
    public static int rows(MemorySegment struct) {
        return struct.get(rows$LAYOUT, rows$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int rows
     * }
     */
    public static void rows(MemorySegment struct, int fieldValue) {
        struct.set(rows$LAYOUT, rows$OFFSET, fieldValue);
    }

    private static final OfInt cols$LAYOUT = (OfInt)$LAYOUT.select(groupElement("cols"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int cols
     * }
     */
    public static final OfInt cols$layout() {
        return cols$LAYOUT;
    }

    private static final long cols$OFFSET = $LAYOUT.byteOffset(groupElement("cols"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int cols
     * }
     */
    public static final long cols$offset() {
        return cols$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int cols
     * }
     */
    public static int cols(MemorySegment struct) {
        return struct.get(cols$LAYOUT, cols$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int cols
     * }
     */
    public static void cols(MemorySegment struct, int fieldValue) {
        struct.set(cols$LAYOUT, cols$OFFSET, fieldValue);
    }

    private static final SequenceLayout delta_q$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("delta_q"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int delta_q[8]
     * }
     */
    public static final SequenceLayout delta_q$layout() {
        return delta_q$LAYOUT;
    }

    private static final long delta_q$OFFSET = $LAYOUT.byteOffset(groupElement("delta_q"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int delta_q[8]
     * }
     */
    public static final long delta_q$offset() {
        return delta_q$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int delta_q[8]
     * }
     */
    public static MemorySegment delta_q(MemorySegment struct) {
        return struct.asSlice(delta_q$OFFSET, delta_q$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int delta_q[8]
     * }
     */
    public static void delta_q(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, delta_q$OFFSET, delta_q$LAYOUT.byteSize());
    }

    private static long[] delta_q$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int delta_q[8]
     * }
     */
    public static long[] delta_q$dimensions() {
        return delta_q$DIMS;
    }
    private static final VarHandle delta_q$ELEM_HANDLE = delta_q$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int delta_q[8]
     * }
     */
    public static int delta_q(MemorySegment struct, long index0) {
        return (int)delta_q$ELEM_HANDLE.get(struct, delta_q$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int delta_q[8]
     * }
     */
    public static void delta_q(MemorySegment struct, long index0, int fieldValue) {
        delta_q$ELEM_HANDLE.set(struct, delta_q$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout delta_lf$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("delta_lf"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int delta_lf[8]
     * }
     */
    public static final SequenceLayout delta_lf$layout() {
        return delta_lf$LAYOUT;
    }

    private static final long delta_lf$OFFSET = $LAYOUT.byteOffset(groupElement("delta_lf"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int delta_lf[8]
     * }
     */
    public static final long delta_lf$offset() {
        return delta_lf$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int delta_lf[8]
     * }
     */
    public static MemorySegment delta_lf(MemorySegment struct) {
        return struct.asSlice(delta_lf$OFFSET, delta_lf$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int delta_lf[8]
     * }
     */
    public static void delta_lf(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, delta_lf$OFFSET, delta_lf$LAYOUT.byteSize());
    }

    private static long[] delta_lf$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int delta_lf[8]
     * }
     */
    public static long[] delta_lf$dimensions() {
        return delta_lf$DIMS;
    }
    private static final VarHandle delta_lf$ELEM_HANDLE = delta_lf$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int delta_lf[8]
     * }
     */
    public static int delta_lf(MemorySegment struct, long index0) {
        return (int)delta_lf$ELEM_HANDLE.get(struct, delta_lf$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int delta_lf[8]
     * }
     */
    public static void delta_lf(MemorySegment struct, long index0, int fieldValue) {
        delta_lf$ELEM_HANDLE.set(struct, delta_lf$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout skip$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("skip"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int skip[8]
     * }
     */
    public static final SequenceLayout skip$layout() {
        return skip$LAYOUT;
    }

    private static final long skip$OFFSET = $LAYOUT.byteOffset(groupElement("skip"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int skip[8]
     * }
     */
    public static final long skip$offset() {
        return skip$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int skip[8]
     * }
     */
    public static MemorySegment skip(MemorySegment struct) {
        return struct.asSlice(skip$OFFSET, skip$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int skip[8]
     * }
     */
    public static void skip(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, skip$OFFSET, skip$LAYOUT.byteSize());
    }

    private static long[] skip$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int skip[8]
     * }
     */
    public static long[] skip$dimensions() {
        return skip$DIMS;
    }
    private static final VarHandle skip$ELEM_HANDLE = skip$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int skip[8]
     * }
     */
    public static int skip(MemorySegment struct, long index0) {
        return (int)skip$ELEM_HANDLE.get(struct, skip$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int skip[8]
     * }
     */
    public static void skip(MemorySegment struct, long index0, int fieldValue) {
        skip$ELEM_HANDLE.set(struct, skip$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout ref_frame$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("ref_frame"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int ref_frame[8]
     * }
     */
    public static final SequenceLayout ref_frame$layout() {
        return ref_frame$LAYOUT;
    }

    private static final long ref_frame$OFFSET = $LAYOUT.byteOffset(groupElement("ref_frame"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int ref_frame[8]
     * }
     */
    public static final long ref_frame$offset() {
        return ref_frame$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int ref_frame[8]
     * }
     */
    public static MemorySegment ref_frame(MemorySegment struct) {
        return struct.asSlice(ref_frame$OFFSET, ref_frame$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int ref_frame[8]
     * }
     */
    public static void ref_frame(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ref_frame$OFFSET, ref_frame$LAYOUT.byteSize());
    }

    private static long[] ref_frame$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int ref_frame[8]
     * }
     */
    public static long[] ref_frame$dimensions() {
        return ref_frame$DIMS;
    }
    private static final VarHandle ref_frame$ELEM_HANDLE = ref_frame$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int ref_frame[8]
     * }
     */
    public static int ref_frame(MemorySegment struct, long index0) {
        return (int)ref_frame$ELEM_HANDLE.get(struct, ref_frame$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int ref_frame[8]
     * }
     */
    public static void ref_frame(MemorySegment struct, long index0, int fieldValue) {
        ref_frame$ELEM_HANDLE.set(struct, ref_frame$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout static_threshold$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("static_threshold"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int static_threshold[4]
     * }
     */
    public static final SequenceLayout static_threshold$layout() {
        return static_threshold$LAYOUT;
    }

    private static final long static_threshold$OFFSET = $LAYOUT.byteOffset(groupElement("static_threshold"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int static_threshold[4]
     * }
     */
    public static final long static_threshold$offset() {
        return static_threshold$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int static_threshold[4]
     * }
     */
    public static MemorySegment static_threshold(MemorySegment struct) {
        return struct.asSlice(static_threshold$OFFSET, static_threshold$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int static_threshold[4]
     * }
     */
    public static void static_threshold(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, static_threshold$OFFSET, static_threshold$LAYOUT.byteSize());
    }

    private static long[] static_threshold$DIMS = { 4 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * unsigned int static_threshold[4]
     * }
     */
    public static long[] static_threshold$dimensions() {
        return static_threshold$DIMS;
    }
    private static final VarHandle static_threshold$ELEM_HANDLE = static_threshold$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * unsigned int static_threshold[4]
     * }
     */
    public static int static_threshold(MemorySegment struct, long index0) {
        return (int)static_threshold$ELEM_HANDLE.get(struct, static_threshold$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * unsigned int static_threshold[4]
     * }
     */
    public static void static_threshold(MemorySegment struct, long index0, int fieldValue) {
        static_threshold$ELEM_HANDLE.set(struct, static_threshold$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

