// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_codec_enc_output_cx_cb_pair {
 *     vpx_codec_enc_output_cx_pkt_cb_fn_t output_cx_pkt;
 *     void *user_priv;
 * }
 * }
 */
public class vpx_codec_enc_output_cx_cb_pair {

    vpx_codec_enc_output_cx_cb_pair() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_POINTER.withName("output_cx_pkt"),
        VpxFFI.C_POINTER.withName("user_priv")
    ).withName("vpx_codec_enc_output_cx_cb_pair");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout output_cx_pkt$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("output_cx_pkt"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_codec_enc_output_cx_pkt_cb_fn_t output_cx_pkt
     * }
     */
    public static final AddressLayout output_cx_pkt$layout() {
        return output_cx_pkt$LAYOUT;
    }

    private static final long output_cx_pkt$OFFSET = $LAYOUT.byteOffset(groupElement("output_cx_pkt"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_codec_enc_output_cx_pkt_cb_fn_t output_cx_pkt
     * }
     */
    public static final long output_cx_pkt$offset() {
        return output_cx_pkt$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_codec_enc_output_cx_pkt_cb_fn_t output_cx_pkt
     * }
     */
    public static MemorySegment output_cx_pkt(MemorySegment struct) {
        return struct.get(output_cx_pkt$LAYOUT, output_cx_pkt$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_codec_enc_output_cx_pkt_cb_fn_t output_cx_pkt
     * }
     */
    public static void output_cx_pkt(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(output_cx_pkt$LAYOUT, output_cx_pkt$OFFSET, fieldValue);
    }

    private static final AddressLayout user_priv$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("user_priv"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *user_priv
     * }
     */
    public static final AddressLayout user_priv$layout() {
        return user_priv$LAYOUT;
    }

    private static final long user_priv$OFFSET = $LAYOUT.byteOffset(groupElement("user_priv"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *user_priv
     * }
     */
    public static final long user_priv$offset() {
        return user_priv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *user_priv
     * }
     */
    public static MemorySegment user_priv(MemorySegment struct) {
        return struct.get(user_priv$LAYOUT, user_priv$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *user_priv
     * }
     */
    public static void user_priv(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(user_priv$LAYOUT, user_priv$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

