// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_rc_gop_decision {
 *     int gop_coding_frames;
 *     int use_alt_ref;
 *     int use_key_frame;
 *     vpx_rc_frame_update_type_t update_type[252];
 *     int update_ref_index[252];
 *     vpx_rc_ref_frame_t ref_frame_list[252];
 * }
 * }
 */
public class vpx_rc_gop_decision {

    vpx_rc_gop_decision() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_INT.withName("gop_coding_frames"),
        VpxFFI.C_INT.withName("use_alt_ref"),
        VpxFFI.C_INT.withName("use_key_frame"),
        MemoryLayout.sequenceLayout(252, VpxFFI.C_INT).withName("update_type"),
        MemoryLayout.sequenceLayout(252, VpxFFI.C_INT).withName("update_ref_index"),
        MemoryLayout.sequenceLayout(252, vpx_rc_ref_frame.layout()).withName("ref_frame_list")
    ).withName("vpx_rc_gop_decision");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt gop_coding_frames$LAYOUT = (OfInt)$LAYOUT.select(groupElement("gop_coding_frames"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int gop_coding_frames
     * }
     */
    public static final OfInt gop_coding_frames$layout() {
        return gop_coding_frames$LAYOUT;
    }

    private static final long gop_coding_frames$OFFSET = $LAYOUT.byteOffset(groupElement("gop_coding_frames"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int gop_coding_frames
     * }
     */
    public static final long gop_coding_frames$offset() {
        return gop_coding_frames$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int gop_coding_frames
     * }
     */
    public static int gop_coding_frames(MemorySegment struct) {
        return struct.get(gop_coding_frames$LAYOUT, gop_coding_frames$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int gop_coding_frames
     * }
     */
    public static void gop_coding_frames(MemorySegment struct, int fieldValue) {
        struct.set(gop_coding_frames$LAYOUT, gop_coding_frames$OFFSET, fieldValue);
    }

    private static final OfInt use_alt_ref$LAYOUT = (OfInt)$LAYOUT.select(groupElement("use_alt_ref"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int use_alt_ref
     * }
     */
    public static final OfInt use_alt_ref$layout() {
        return use_alt_ref$LAYOUT;
    }

    private static final long use_alt_ref$OFFSET = $LAYOUT.byteOffset(groupElement("use_alt_ref"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int use_alt_ref
     * }
     */
    public static final long use_alt_ref$offset() {
        return use_alt_ref$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int use_alt_ref
     * }
     */
    public static int use_alt_ref(MemorySegment struct) {
        return struct.get(use_alt_ref$LAYOUT, use_alt_ref$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int use_alt_ref
     * }
     */
    public static void use_alt_ref(MemorySegment struct, int fieldValue) {
        struct.set(use_alt_ref$LAYOUT, use_alt_ref$OFFSET, fieldValue);
    }

    private static final OfInt use_key_frame$LAYOUT = (OfInt)$LAYOUT.select(groupElement("use_key_frame"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int use_key_frame
     * }
     */
    public static final OfInt use_key_frame$layout() {
        return use_key_frame$LAYOUT;
    }

    private static final long use_key_frame$OFFSET = $LAYOUT.byteOffset(groupElement("use_key_frame"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int use_key_frame
     * }
     */
    public static final long use_key_frame$offset() {
        return use_key_frame$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int use_key_frame
     * }
     */
    public static int use_key_frame(MemorySegment struct) {
        return struct.get(use_key_frame$LAYOUT, use_key_frame$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int use_key_frame
     * }
     */
    public static void use_key_frame(MemorySegment struct, int fieldValue) {
        struct.set(use_key_frame$LAYOUT, use_key_frame$OFFSET, fieldValue);
    }

    private static final SequenceLayout update_type$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("update_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_rc_frame_update_type_t update_type[252]
     * }
     */
    public static final SequenceLayout update_type$layout() {
        return update_type$LAYOUT;
    }

    private static final long update_type$OFFSET = $LAYOUT.byteOffset(groupElement("update_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_rc_frame_update_type_t update_type[252]
     * }
     */
    public static final long update_type$offset() {
        return update_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_rc_frame_update_type_t update_type[252]
     * }
     */
    public static MemorySegment update_type(MemorySegment struct) {
        return struct.asSlice(update_type$OFFSET, update_type$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_rc_frame_update_type_t update_type[252]
     * }
     */
    public static void update_type(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, update_type$OFFSET, update_type$LAYOUT.byteSize());
    }

    private static long[] update_type$DIMS = { 252 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * vpx_rc_frame_update_type_t update_type[252]
     * }
     */
    public static long[] update_type$dimensions() {
        return update_type$DIMS;
    }
    private static final VarHandle update_type$ELEM_HANDLE = update_type$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * vpx_rc_frame_update_type_t update_type[252]
     * }
     */
    public static int update_type(MemorySegment struct, long index0) {
        return (int)update_type$ELEM_HANDLE.get(struct, update_type$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * vpx_rc_frame_update_type_t update_type[252]
     * }
     */
    public static void update_type(MemorySegment struct, long index0, int fieldValue) {
        update_type$ELEM_HANDLE.set(struct, update_type$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout update_ref_index$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("update_ref_index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int update_ref_index[252]
     * }
     */
    public static final SequenceLayout update_ref_index$layout() {
        return update_ref_index$LAYOUT;
    }

    private static final long update_ref_index$OFFSET = $LAYOUT.byteOffset(groupElement("update_ref_index"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int update_ref_index[252]
     * }
     */
    public static final long update_ref_index$offset() {
        return update_ref_index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int update_ref_index[252]
     * }
     */
    public static MemorySegment update_ref_index(MemorySegment struct) {
        return struct.asSlice(update_ref_index$OFFSET, update_ref_index$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int update_ref_index[252]
     * }
     */
    public static void update_ref_index(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, update_ref_index$OFFSET, update_ref_index$LAYOUT.byteSize());
    }

    private static long[] update_ref_index$DIMS = { 252 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int update_ref_index[252]
     * }
     */
    public static long[] update_ref_index$dimensions() {
        return update_ref_index$DIMS;
    }
    private static final VarHandle update_ref_index$ELEM_HANDLE = update_ref_index$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int update_ref_index[252]
     * }
     */
    public static int update_ref_index(MemorySegment struct, long index0) {
        return (int)update_ref_index$ELEM_HANDLE.get(struct, update_ref_index$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int update_ref_index[252]
     * }
     */
    public static void update_ref_index(MemorySegment struct, long index0, int fieldValue) {
        update_ref_index$ELEM_HANDLE.set(struct, update_ref_index$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout ref_frame_list$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("ref_frame_list"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_rc_ref_frame_t ref_frame_list[252]
     * }
     */
    public static final SequenceLayout ref_frame_list$layout() {
        return ref_frame_list$LAYOUT;
    }

    private static final long ref_frame_list$OFFSET = $LAYOUT.byteOffset(groupElement("ref_frame_list"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_rc_ref_frame_t ref_frame_list[252]
     * }
     */
    public static final long ref_frame_list$offset() {
        return ref_frame_list$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_rc_ref_frame_t ref_frame_list[252]
     * }
     */
    public static MemorySegment ref_frame_list(MemorySegment struct) {
        return struct.asSlice(ref_frame_list$OFFSET, ref_frame_list$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_rc_ref_frame_t ref_frame_list[252]
     * }
     */
    public static void ref_frame_list(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ref_frame_list$OFFSET, ref_frame_list$LAYOUT.byteSize());
    }

    private static long[] ref_frame_list$DIMS = { 252 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * vpx_rc_ref_frame_t ref_frame_list[252]
     * }
     */
    public static long[] ref_frame_list$dimensions() {
        return ref_frame_list$DIMS;
    }
    private static final MethodHandle ref_frame_list$ELEM_HANDLE = ref_frame_list$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * vpx_rc_ref_frame_t ref_frame_list[252]
     * }
     */
    public static MemorySegment ref_frame_list(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)ref_frame_list$ELEM_HANDLE.invokeExact(struct, ref_frame_list$OFFSET, index0);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * vpx_rc_ref_frame_t ref_frame_list[252]
     * }
     */
    public static void ref_frame_list(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, ref_frame_list(struct, index0), 0L, vpx_rc_ref_frame.layout().byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

