// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_active_map {
 *     unsigned char *active_map;
 *     unsigned int rows;
 *     unsigned int cols;
 * }
 * }
 */
public class vpx_active_map {

    vpx_active_map() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_POINTER.withName("active_map"),
        VpxFFI.C_INT.withName("rows"),
        VpxFFI.C_INT.withName("cols")
    ).withName("vpx_active_map");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout active_map$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("active_map"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char *active_map
     * }
     */
    public static final AddressLayout active_map$layout() {
        return active_map$LAYOUT;
    }

    private static final long active_map$OFFSET = $LAYOUT.byteOffset(groupElement("active_map"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char *active_map
     * }
     */
    public static final long active_map$offset() {
        return active_map$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char *active_map
     * }
     */
    public static MemorySegment active_map(MemorySegment struct) {
        return struct.get(active_map$LAYOUT, active_map$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char *active_map
     * }
     */
    public static void active_map(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(active_map$LAYOUT, active_map$OFFSET, fieldValue);
    }

    private static final OfInt rows$LAYOUT = (OfInt)$LAYOUT.select(groupElement("rows"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int rows
     * }
     */
    public static final OfInt rows$layout() {
        return rows$LAYOUT;
    }

    private static final long rows$OFFSET = $LAYOUT.byteOffset(groupElement("rows"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int rows
     * }
     */
    public static final long rows$offset() {
        return rows$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int rows
     * }
     */
    public static int rows(MemorySegment struct) {
        return struct.get(rows$LAYOUT, rows$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int rows
     * }
     */
    public static void rows(MemorySegment struct, int fieldValue) {
        struct.set(rows$LAYOUT, rows$OFFSET, fieldValue);
    }

    private static final OfInt cols$LAYOUT = (OfInt)$LAYOUT.select(groupElement("cols"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int cols
     * }
     */
    public static final OfInt cols$layout() {
        return cols$LAYOUT;
    }

    private static final long cols$OFFSET = $LAYOUT.byteOffset(groupElement("cols"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int cols
     * }
     */
    public static final long cols$offset() {
        return cols$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int cols
     * }
     */
    public static int cols(MemorySegment struct) {
        return struct.get(cols$LAYOUT, cols$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int cols
     * }
     */
    public static void cols(MemorySegment struct, int fieldValue) {
        struct.set(cols$LAYOUT, cols$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

