// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_codec_ctx {
 *     const char *name;
 *     vpx_codec_iface_t *iface;
 *     vpx_codec_err_t err;
 *     const char *err_detail;
 *     vpx_codec_flags_t init_flags;
 *     union {
 *         const struct vpx_codec_dec_cfg *dec;
 *         const struct vpx_codec_enc_cfg *enc;
 *         const void *raw;
 *     } config;
 *     vpx_codec_priv_t *priv;
 * } vpx_codec_ctx_t
 * }
 */
public class vpx_codec_ctx_t extends vpx_codec_ctx {

    vpx_codec_ctx_t() {
        // Should not be called directly
    }
}

