// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_codec_dec_cfg {
 *     unsigned int threads;
 *     unsigned int w;
 *     unsigned int h;
 * } vpx_codec_dec_cfg_t
 * }
 */
public class vpx_codec_dec_cfg_t extends vpx_codec_dec_cfg {

    vpx_codec_dec_cfg_t() {
        // Should not be called directly
    }
}

