// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_rc_firstpass_stats {
 *     vpx_rc_frame_stats_t *frame_stats;
 *     int num_frames;
 * }
 * }
 */
public class vpx_rc_firstpass_stats {

    vpx_rc_firstpass_stats() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_POINTER.withName("frame_stats"),
        VpxFFI.C_INT.withName("num_frames"),
        MemoryLayout.paddingLayout(4)
    ).withName("vpx_rc_firstpass_stats");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout frame_stats$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("frame_stats"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_rc_frame_stats_t *frame_stats
     * }
     */
    public static final AddressLayout frame_stats$layout() {
        return frame_stats$LAYOUT;
    }

    private static final long frame_stats$OFFSET = $LAYOUT.byteOffset(groupElement("frame_stats"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_rc_frame_stats_t *frame_stats
     * }
     */
    public static final long frame_stats$offset() {
        return frame_stats$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_rc_frame_stats_t *frame_stats
     * }
     */
    public static MemorySegment frame_stats(MemorySegment struct) {
        return struct.get(frame_stats$LAYOUT, frame_stats$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_rc_frame_stats_t *frame_stats
     * }
     */
    public static void frame_stats(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(frame_stats$LAYOUT, frame_stats$OFFSET, fieldValue);
    }

    private static final OfInt num_frames$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_frames"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int num_frames
     * }
     */
    public static final OfInt num_frames$layout() {
        return num_frames$LAYOUT;
    }

    private static final long num_frames$OFFSET = $LAYOUT.byteOffset(groupElement("num_frames"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int num_frames
     * }
     */
    public static final long num_frames$offset() {
        return num_frames$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int num_frames
     * }
     */
    public static int num_frames(MemorySegment struct) {
        return struct.get(num_frames$LAYOUT, num_frames$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int num_frames
     * }
     */
    public static void num_frames(MemorySegment struct, int fieldValue) {
        struct.set(num_frames$LAYOUT, num_frames$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

