// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_rc_firstpass_stats {
 *     vpx_rc_frame_stats_t *frame_stats;
 *     int num_frames;
 * } vpx_rc_firstpass_stats_t
 * }
 */
public class vpx_rc_firstpass_stats_t extends vpx_rc_firstpass_stats {

    vpx_rc_firstpass_stats_t() {
        // Should not be called directly
    }
}

