// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_rc_config {
 *     int frame_width;
 *     int frame_height;
 *     int show_frame_count;
 *     int max_gf_interval;
 *     int min_gf_interval;
 *     int target_bitrate_kbps;
 *     int frame_rate_num;
 *     int frame_rate_den;
 *     vpx_ext_rc_mode_t rc_mode;
 *     int overshoot_percent;
 *     int undershoot_percent;
 *     int min_base_q_index;
 *     int max_base_q_index;
 *     int base_qp;
 * }
 * }
 */
public class vpx_rc_config {

    vpx_rc_config() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_INT.withName("frame_width"),
        VpxFFI.C_INT.withName("frame_height"),
        VpxFFI.C_INT.withName("show_frame_count"),
        VpxFFI.C_INT.withName("max_gf_interval"),
        VpxFFI.C_INT.withName("min_gf_interval"),
        VpxFFI.C_INT.withName("target_bitrate_kbps"),
        VpxFFI.C_INT.withName("frame_rate_num"),
        VpxFFI.C_INT.withName("frame_rate_den"),
        VpxFFI.C_INT.withName("rc_mode"),
        VpxFFI.C_INT.withName("overshoot_percent"),
        VpxFFI.C_INT.withName("undershoot_percent"),
        VpxFFI.C_INT.withName("min_base_q_index"),
        VpxFFI.C_INT.withName("max_base_q_index"),
        VpxFFI.C_INT.withName("base_qp")
    ).withName("vpx_rc_config");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt frame_width$LAYOUT = (OfInt)$LAYOUT.select(groupElement("frame_width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int frame_width
     * }
     */
    public static final OfInt frame_width$layout() {
        return frame_width$LAYOUT;
    }

    private static final long frame_width$OFFSET = $LAYOUT.byteOffset(groupElement("frame_width"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int frame_width
     * }
     */
    public static final long frame_width$offset() {
        return frame_width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int frame_width
     * }
     */
    public static int frame_width(MemorySegment struct) {
        return struct.get(frame_width$LAYOUT, frame_width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int frame_width
     * }
     */
    public static void frame_width(MemorySegment struct, int fieldValue) {
        struct.set(frame_width$LAYOUT, frame_width$OFFSET, fieldValue);
    }

    private static final OfInt frame_height$LAYOUT = (OfInt)$LAYOUT.select(groupElement("frame_height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int frame_height
     * }
     */
    public static final OfInt frame_height$layout() {
        return frame_height$LAYOUT;
    }

    private static final long frame_height$OFFSET = $LAYOUT.byteOffset(groupElement("frame_height"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int frame_height
     * }
     */
    public static final long frame_height$offset() {
        return frame_height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int frame_height
     * }
     */
    public static int frame_height(MemorySegment struct) {
        return struct.get(frame_height$LAYOUT, frame_height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int frame_height
     * }
     */
    public static void frame_height(MemorySegment struct, int fieldValue) {
        struct.set(frame_height$LAYOUT, frame_height$OFFSET, fieldValue);
    }

    private static final OfInt show_frame_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("show_frame_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int show_frame_count
     * }
     */
    public static final OfInt show_frame_count$layout() {
        return show_frame_count$LAYOUT;
    }

    private static final long show_frame_count$OFFSET = $LAYOUT.byteOffset(groupElement("show_frame_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int show_frame_count
     * }
     */
    public static final long show_frame_count$offset() {
        return show_frame_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int show_frame_count
     * }
     */
    public static int show_frame_count(MemorySegment struct) {
        return struct.get(show_frame_count$LAYOUT, show_frame_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int show_frame_count
     * }
     */
    public static void show_frame_count(MemorySegment struct, int fieldValue) {
        struct.set(show_frame_count$LAYOUT, show_frame_count$OFFSET, fieldValue);
    }

    private static final OfInt max_gf_interval$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_gf_interval"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int max_gf_interval
     * }
     */
    public static final OfInt max_gf_interval$layout() {
        return max_gf_interval$LAYOUT;
    }

    private static final long max_gf_interval$OFFSET = $LAYOUT.byteOffset(groupElement("max_gf_interval"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int max_gf_interval
     * }
     */
    public static final long max_gf_interval$offset() {
        return max_gf_interval$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int max_gf_interval
     * }
     */
    public static int max_gf_interval(MemorySegment struct) {
        return struct.get(max_gf_interval$LAYOUT, max_gf_interval$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int max_gf_interval
     * }
     */
    public static void max_gf_interval(MemorySegment struct, int fieldValue) {
        struct.set(max_gf_interval$LAYOUT, max_gf_interval$OFFSET, fieldValue);
    }

    private static final OfInt min_gf_interval$LAYOUT = (OfInt)$LAYOUT.select(groupElement("min_gf_interval"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int min_gf_interval
     * }
     */
    public static final OfInt min_gf_interval$layout() {
        return min_gf_interval$LAYOUT;
    }

    private static final long min_gf_interval$OFFSET = $LAYOUT.byteOffset(groupElement("min_gf_interval"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int min_gf_interval
     * }
     */
    public static final long min_gf_interval$offset() {
        return min_gf_interval$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int min_gf_interval
     * }
     */
    public static int min_gf_interval(MemorySegment struct) {
        return struct.get(min_gf_interval$LAYOUT, min_gf_interval$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int min_gf_interval
     * }
     */
    public static void min_gf_interval(MemorySegment struct, int fieldValue) {
        struct.set(min_gf_interval$LAYOUT, min_gf_interval$OFFSET, fieldValue);
    }

    private static final OfInt target_bitrate_kbps$LAYOUT = (OfInt)$LAYOUT.select(groupElement("target_bitrate_kbps"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int target_bitrate_kbps
     * }
     */
    public static final OfInt target_bitrate_kbps$layout() {
        return target_bitrate_kbps$LAYOUT;
    }

    private static final long target_bitrate_kbps$OFFSET = $LAYOUT.byteOffset(groupElement("target_bitrate_kbps"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int target_bitrate_kbps
     * }
     */
    public static final long target_bitrate_kbps$offset() {
        return target_bitrate_kbps$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int target_bitrate_kbps
     * }
     */
    public static int target_bitrate_kbps(MemorySegment struct) {
        return struct.get(target_bitrate_kbps$LAYOUT, target_bitrate_kbps$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int target_bitrate_kbps
     * }
     */
    public static void target_bitrate_kbps(MemorySegment struct, int fieldValue) {
        struct.set(target_bitrate_kbps$LAYOUT, target_bitrate_kbps$OFFSET, fieldValue);
    }

    private static final OfInt frame_rate_num$LAYOUT = (OfInt)$LAYOUT.select(groupElement("frame_rate_num"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int frame_rate_num
     * }
     */
    public static final OfInt frame_rate_num$layout() {
        return frame_rate_num$LAYOUT;
    }

    private static final long frame_rate_num$OFFSET = $LAYOUT.byteOffset(groupElement("frame_rate_num"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int frame_rate_num
     * }
     */
    public static final long frame_rate_num$offset() {
        return frame_rate_num$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int frame_rate_num
     * }
     */
    public static int frame_rate_num(MemorySegment struct) {
        return struct.get(frame_rate_num$LAYOUT, frame_rate_num$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int frame_rate_num
     * }
     */
    public static void frame_rate_num(MemorySegment struct, int fieldValue) {
        struct.set(frame_rate_num$LAYOUT, frame_rate_num$OFFSET, fieldValue);
    }

    private static final OfInt frame_rate_den$LAYOUT = (OfInt)$LAYOUT.select(groupElement("frame_rate_den"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int frame_rate_den
     * }
     */
    public static final OfInt frame_rate_den$layout() {
        return frame_rate_den$LAYOUT;
    }

    private static final long frame_rate_den$OFFSET = $LAYOUT.byteOffset(groupElement("frame_rate_den"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int frame_rate_den
     * }
     */
    public static final long frame_rate_den$offset() {
        return frame_rate_den$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int frame_rate_den
     * }
     */
    public static int frame_rate_den(MemorySegment struct) {
        return struct.get(frame_rate_den$LAYOUT, frame_rate_den$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int frame_rate_den
     * }
     */
    public static void frame_rate_den(MemorySegment struct, int fieldValue) {
        struct.set(frame_rate_den$LAYOUT, frame_rate_den$OFFSET, fieldValue);
    }

    private static final OfInt rc_mode$LAYOUT = (OfInt)$LAYOUT.select(groupElement("rc_mode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_ext_rc_mode_t rc_mode
     * }
     */
    public static final OfInt rc_mode$layout() {
        return rc_mode$LAYOUT;
    }

    private static final long rc_mode$OFFSET = $LAYOUT.byteOffset(groupElement("rc_mode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_ext_rc_mode_t rc_mode
     * }
     */
    public static final long rc_mode$offset() {
        return rc_mode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_ext_rc_mode_t rc_mode
     * }
     */
    public static int rc_mode(MemorySegment struct) {
        return struct.get(rc_mode$LAYOUT, rc_mode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_ext_rc_mode_t rc_mode
     * }
     */
    public static void rc_mode(MemorySegment struct, int fieldValue) {
        struct.set(rc_mode$LAYOUT, rc_mode$OFFSET, fieldValue);
    }

    private static final OfInt overshoot_percent$LAYOUT = (OfInt)$LAYOUT.select(groupElement("overshoot_percent"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int overshoot_percent
     * }
     */
    public static final OfInt overshoot_percent$layout() {
        return overshoot_percent$LAYOUT;
    }

    private static final long overshoot_percent$OFFSET = $LAYOUT.byteOffset(groupElement("overshoot_percent"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int overshoot_percent
     * }
     */
    public static final long overshoot_percent$offset() {
        return overshoot_percent$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int overshoot_percent
     * }
     */
    public static int overshoot_percent(MemorySegment struct) {
        return struct.get(overshoot_percent$LAYOUT, overshoot_percent$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int overshoot_percent
     * }
     */
    public static void overshoot_percent(MemorySegment struct, int fieldValue) {
        struct.set(overshoot_percent$LAYOUT, overshoot_percent$OFFSET, fieldValue);
    }

    private static final OfInt undershoot_percent$LAYOUT = (OfInt)$LAYOUT.select(groupElement("undershoot_percent"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int undershoot_percent
     * }
     */
    public static final OfInt undershoot_percent$layout() {
        return undershoot_percent$LAYOUT;
    }

    private static final long undershoot_percent$OFFSET = $LAYOUT.byteOffset(groupElement("undershoot_percent"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int undershoot_percent
     * }
     */
    public static final long undershoot_percent$offset() {
        return undershoot_percent$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int undershoot_percent
     * }
     */
    public static int undershoot_percent(MemorySegment struct) {
        return struct.get(undershoot_percent$LAYOUT, undershoot_percent$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int undershoot_percent
     * }
     */
    public static void undershoot_percent(MemorySegment struct, int fieldValue) {
        struct.set(undershoot_percent$LAYOUT, undershoot_percent$OFFSET, fieldValue);
    }

    private static final OfInt min_base_q_index$LAYOUT = (OfInt)$LAYOUT.select(groupElement("min_base_q_index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int min_base_q_index
     * }
     */
    public static final OfInt min_base_q_index$layout() {
        return min_base_q_index$LAYOUT;
    }

    private static final long min_base_q_index$OFFSET = $LAYOUT.byteOffset(groupElement("min_base_q_index"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int min_base_q_index
     * }
     */
    public static final long min_base_q_index$offset() {
        return min_base_q_index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int min_base_q_index
     * }
     */
    public static int min_base_q_index(MemorySegment struct) {
        return struct.get(min_base_q_index$LAYOUT, min_base_q_index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int min_base_q_index
     * }
     */
    public static void min_base_q_index(MemorySegment struct, int fieldValue) {
        struct.set(min_base_q_index$LAYOUT, min_base_q_index$OFFSET, fieldValue);
    }

    private static final OfInt max_base_q_index$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_base_q_index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int max_base_q_index
     * }
     */
    public static final OfInt max_base_q_index$layout() {
        return max_base_q_index$LAYOUT;
    }

    private static final long max_base_q_index$OFFSET = $LAYOUT.byteOffset(groupElement("max_base_q_index"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int max_base_q_index
     * }
     */
    public static final long max_base_q_index$offset() {
        return max_base_q_index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int max_base_q_index
     * }
     */
    public static int max_base_q_index(MemorySegment struct) {
        return struct.get(max_base_q_index$LAYOUT, max_base_q_index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int max_base_q_index
     * }
     */
    public static void max_base_q_index(MemorySegment struct, int fieldValue) {
        struct.set(max_base_q_index$LAYOUT, max_base_q_index$OFFSET, fieldValue);
    }

    private static final OfInt base_qp$LAYOUT = (OfInt)$LAYOUT.select(groupElement("base_qp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int base_qp
     * }
     */
    public static final OfInt base_qp$layout() {
        return base_qp$LAYOUT;
    }

    private static final long base_qp$OFFSET = $LAYOUT.byteOffset(groupElement("base_qp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int base_qp
     * }
     */
    public static final long base_qp$offset() {
        return base_qp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int base_qp
     * }
     */
    public static int base_qp(MemorySegment struct) {
        return struct.get(base_qp$LAYOUT, base_qp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int base_qp
     * }
     */
    public static void base_qp(MemorySegment struct, int fieldValue) {
        struct.set(base_qp$LAYOUT, base_qp$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

