// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_rc_funcs {
 *     vpx_rc_type_t rc_type;
 *     vpx_rc_create_model_cb_fn_t create_model;
 *     vpx_rc_send_firstpass_stats_cb_fn_t send_firstpass_stats;
 *     vpx_rc_send_tpl_gop_stats_cb_fn_t send_tpl_gop_stats;
 *     vpx_rc_get_encodeframe_decision_cb_fn_t get_encodeframe_decision;
 *     vpx_rc_update_encodeframe_result_cb_fn_t update_encodeframe_result;
 *     vpx_rc_get_key_frame_decision_cb_fn_t get_key_frame_decision;
 *     vpx_rc_get_gop_decision_cb_fn_t get_gop_decision;
 *     vpx_rc_get_frame_rdmult_cb_fn_t get_frame_rdmult;
 *     vpx_rc_delete_model_cb_fn_t delete_model;
 *     const char *rate_ctrl_log_path;
 *     void *priv;
 * } vpx_rc_funcs_t
 * }
 */
public class vpx_rc_funcs_t extends vpx_rc_funcs {

    vpx_rc_funcs_t() {
        // Should not be called directly
    }
}

