// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_rc_encodeframe_info {
 *     int frame_type;
 *     int show_index;
 *     int coding_index;
 *     int gop_index;
 *     int ref_frame_coding_indexes[3];
 *     int ref_frame_valid_list[3];
 *     int gop_size;
 *     int use_alt_ref;
 * }
 * }
 */
public class vpx_rc_encodeframe_info {

    vpx_rc_encodeframe_info() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_INT.withName("frame_type"),
        VpxFFI.C_INT.withName("show_index"),
        VpxFFI.C_INT.withName("coding_index"),
        VpxFFI.C_INT.withName("gop_index"),
        MemoryLayout.sequenceLayout(3, VpxFFI.C_INT).withName("ref_frame_coding_indexes"),
        MemoryLayout.sequenceLayout(3, VpxFFI.C_INT).withName("ref_frame_valid_list"),
        VpxFFI.C_INT.withName("gop_size"),
        VpxFFI.C_INT.withName("use_alt_ref")
    ).withName("vpx_rc_encodeframe_info");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt frame_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("frame_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int frame_type
     * }
     */
    public static final OfInt frame_type$layout() {
        return frame_type$LAYOUT;
    }

    private static final long frame_type$OFFSET = $LAYOUT.byteOffset(groupElement("frame_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int frame_type
     * }
     */
    public static final long frame_type$offset() {
        return frame_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int frame_type
     * }
     */
    public static int frame_type(MemorySegment struct) {
        return struct.get(frame_type$LAYOUT, frame_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int frame_type
     * }
     */
    public static void frame_type(MemorySegment struct, int fieldValue) {
        struct.set(frame_type$LAYOUT, frame_type$OFFSET, fieldValue);
    }

    private static final OfInt show_index$LAYOUT = (OfInt)$LAYOUT.select(groupElement("show_index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int show_index
     * }
     */
    public static final OfInt show_index$layout() {
        return show_index$LAYOUT;
    }

    private static final long show_index$OFFSET = $LAYOUT.byteOffset(groupElement("show_index"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int show_index
     * }
     */
    public static final long show_index$offset() {
        return show_index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int show_index
     * }
     */
    public static int show_index(MemorySegment struct) {
        return struct.get(show_index$LAYOUT, show_index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int show_index
     * }
     */
    public static void show_index(MemorySegment struct, int fieldValue) {
        struct.set(show_index$LAYOUT, show_index$OFFSET, fieldValue);
    }

    private static final OfInt coding_index$LAYOUT = (OfInt)$LAYOUT.select(groupElement("coding_index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int coding_index
     * }
     */
    public static final OfInt coding_index$layout() {
        return coding_index$LAYOUT;
    }

    private static final long coding_index$OFFSET = $LAYOUT.byteOffset(groupElement("coding_index"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int coding_index
     * }
     */
    public static final long coding_index$offset() {
        return coding_index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int coding_index
     * }
     */
    public static int coding_index(MemorySegment struct) {
        return struct.get(coding_index$LAYOUT, coding_index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int coding_index
     * }
     */
    public static void coding_index(MemorySegment struct, int fieldValue) {
        struct.set(coding_index$LAYOUT, coding_index$OFFSET, fieldValue);
    }

    private static final OfInt gop_index$LAYOUT = (OfInt)$LAYOUT.select(groupElement("gop_index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int gop_index
     * }
     */
    public static final OfInt gop_index$layout() {
        return gop_index$LAYOUT;
    }

    private static final long gop_index$OFFSET = $LAYOUT.byteOffset(groupElement("gop_index"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int gop_index
     * }
     */
    public static final long gop_index$offset() {
        return gop_index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int gop_index
     * }
     */
    public static int gop_index(MemorySegment struct) {
        return struct.get(gop_index$LAYOUT, gop_index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int gop_index
     * }
     */
    public static void gop_index(MemorySegment struct, int fieldValue) {
        struct.set(gop_index$LAYOUT, gop_index$OFFSET, fieldValue);
    }

    private static final SequenceLayout ref_frame_coding_indexes$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("ref_frame_coding_indexes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int ref_frame_coding_indexes[3]
     * }
     */
    public static final SequenceLayout ref_frame_coding_indexes$layout() {
        return ref_frame_coding_indexes$LAYOUT;
    }

    private static final long ref_frame_coding_indexes$OFFSET = $LAYOUT.byteOffset(groupElement("ref_frame_coding_indexes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int ref_frame_coding_indexes[3]
     * }
     */
    public static final long ref_frame_coding_indexes$offset() {
        return ref_frame_coding_indexes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int ref_frame_coding_indexes[3]
     * }
     */
    public static MemorySegment ref_frame_coding_indexes(MemorySegment struct) {
        return struct.asSlice(ref_frame_coding_indexes$OFFSET, ref_frame_coding_indexes$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int ref_frame_coding_indexes[3]
     * }
     */
    public static void ref_frame_coding_indexes(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ref_frame_coding_indexes$OFFSET, ref_frame_coding_indexes$LAYOUT.byteSize());
    }

    private static long[] ref_frame_coding_indexes$DIMS = { 3 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int ref_frame_coding_indexes[3]
     * }
     */
    public static long[] ref_frame_coding_indexes$dimensions() {
        return ref_frame_coding_indexes$DIMS;
    }
    private static final VarHandle ref_frame_coding_indexes$ELEM_HANDLE = ref_frame_coding_indexes$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int ref_frame_coding_indexes[3]
     * }
     */
    public static int ref_frame_coding_indexes(MemorySegment struct, long index0) {
        return (int)ref_frame_coding_indexes$ELEM_HANDLE.get(struct, ref_frame_coding_indexes$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int ref_frame_coding_indexes[3]
     * }
     */
    public static void ref_frame_coding_indexes(MemorySegment struct, long index0, int fieldValue) {
        ref_frame_coding_indexes$ELEM_HANDLE.set(struct, ref_frame_coding_indexes$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout ref_frame_valid_list$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("ref_frame_valid_list"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int ref_frame_valid_list[3]
     * }
     */
    public static final SequenceLayout ref_frame_valid_list$layout() {
        return ref_frame_valid_list$LAYOUT;
    }

    private static final long ref_frame_valid_list$OFFSET = $LAYOUT.byteOffset(groupElement("ref_frame_valid_list"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int ref_frame_valid_list[3]
     * }
     */
    public static final long ref_frame_valid_list$offset() {
        return ref_frame_valid_list$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int ref_frame_valid_list[3]
     * }
     */
    public static MemorySegment ref_frame_valid_list(MemorySegment struct) {
        return struct.asSlice(ref_frame_valid_list$OFFSET, ref_frame_valid_list$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int ref_frame_valid_list[3]
     * }
     */
    public static void ref_frame_valid_list(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ref_frame_valid_list$OFFSET, ref_frame_valid_list$LAYOUT.byteSize());
    }

    private static long[] ref_frame_valid_list$DIMS = { 3 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int ref_frame_valid_list[3]
     * }
     */
    public static long[] ref_frame_valid_list$dimensions() {
        return ref_frame_valid_list$DIMS;
    }
    private static final VarHandle ref_frame_valid_list$ELEM_HANDLE = ref_frame_valid_list$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int ref_frame_valid_list[3]
     * }
     */
    public static int ref_frame_valid_list(MemorySegment struct, long index0) {
        return (int)ref_frame_valid_list$ELEM_HANDLE.get(struct, ref_frame_valid_list$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int ref_frame_valid_list[3]
     * }
     */
    public static void ref_frame_valid_list(MemorySegment struct, long index0, int fieldValue) {
        ref_frame_valid_list$ELEM_HANDLE.set(struct, ref_frame_valid_list$OFFSET, index0, fieldValue);
    }

    private static final OfInt gop_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("gop_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int gop_size
     * }
     */
    public static final OfInt gop_size$layout() {
        return gop_size$LAYOUT;
    }

    private static final long gop_size$OFFSET = $LAYOUT.byteOffset(groupElement("gop_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int gop_size
     * }
     */
    public static final long gop_size$offset() {
        return gop_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int gop_size
     * }
     */
    public static int gop_size(MemorySegment struct) {
        return struct.get(gop_size$LAYOUT, gop_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int gop_size
     * }
     */
    public static void gop_size(MemorySegment struct, int fieldValue) {
        struct.set(gop_size$LAYOUT, gop_size$OFFSET, fieldValue);
    }

    private static final OfInt use_alt_ref$LAYOUT = (OfInt)$LAYOUT.select(groupElement("use_alt_ref"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int use_alt_ref
     * }
     */
    public static final OfInt use_alt_ref$layout() {
        return use_alt_ref$LAYOUT;
    }

    private static final long use_alt_ref$OFFSET = $LAYOUT.byteOffset(groupElement("use_alt_ref"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int use_alt_ref
     * }
     */
    public static final long use_alt_ref$offset() {
        return use_alt_ref$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int use_alt_ref
     * }
     */
    public static int use_alt_ref(MemorySegment struct) {
        return struct.get(use_alt_ref$LAYOUT, use_alt_ref$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int use_alt_ref
     * }
     */
    public static void use_alt_ref(MemorySegment struct, int fieldValue) {
        struct.set(use_alt_ref$LAYOUT, use_alt_ref$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

