// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_decrypt_init {
 *     vpx_decrypt_cb decrypt_cb;
 *     void *decrypt_state;
 * }
 * }
 */
public class vpx_decrypt_init {

    vpx_decrypt_init() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_POINTER.withName("decrypt_cb"),
        VpxFFI.C_POINTER.withName("decrypt_state")
    ).withName("vpx_decrypt_init");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout decrypt_cb$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("decrypt_cb"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_decrypt_cb decrypt_cb
     * }
     */
    public static final AddressLayout decrypt_cb$layout() {
        return decrypt_cb$LAYOUT;
    }

    private static final long decrypt_cb$OFFSET = $LAYOUT.byteOffset(groupElement("decrypt_cb"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_decrypt_cb decrypt_cb
     * }
     */
    public static final long decrypt_cb$offset() {
        return decrypt_cb$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_decrypt_cb decrypt_cb
     * }
     */
    public static MemorySegment decrypt_cb(MemorySegment struct) {
        return struct.get(decrypt_cb$LAYOUT, decrypt_cb$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_decrypt_cb decrypt_cb
     * }
     */
    public static void decrypt_cb(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(decrypt_cb$LAYOUT, decrypt_cb$OFFSET, fieldValue);
    }

    private static final AddressLayout decrypt_state$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("decrypt_state"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *decrypt_state
     * }
     */
    public static final AddressLayout decrypt_state$layout() {
        return decrypt_state$LAYOUT;
    }

    private static final long decrypt_state$OFFSET = $LAYOUT.byteOffset(groupElement("decrypt_state"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *decrypt_state
     * }
     */
    public static final long decrypt_state$offset() {
        return decrypt_state$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *decrypt_state
     * }
     */
    public static MemorySegment decrypt_state(MemorySegment struct) {
        return struct.get(decrypt_state$LAYOUT, decrypt_state$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *decrypt_state
     * }
     */
    public static void decrypt_state(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(decrypt_state$LAYOUT, decrypt_state$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

