// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_fixed_buf {
 *     void *buf;
 *     size_t sz;
 * } vpx_fixed_buf_t
 * }
 */
public class vpx_fixed_buf_t extends vpx_fixed_buf {

    vpx_fixed_buf_t() {
        // Should not be called directly
    }
}

