// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_rc_encodeframe_decision {
 *     int q_index;
 *     int rdmult;
 *     int delta_q_uv;
 *     sb_params *sb_params_list;
 * }
 * }
 */
public class vpx_rc_encodeframe_decision {

    vpx_rc_encodeframe_decision() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_INT.withName("q_index"),
        VpxFFI.C_INT.withName("rdmult"),
        VpxFFI.C_INT.withName("delta_q_uv"),
        MemoryLayout.paddingLayout(4),
        VpxFFI.C_POINTER.withName("sb_params_list")
    ).withName("vpx_rc_encodeframe_decision");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt q_index$LAYOUT = (OfInt)$LAYOUT.select(groupElement("q_index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int q_index
     * }
     */
    public static final OfInt q_index$layout() {
        return q_index$LAYOUT;
    }

    private static final long q_index$OFFSET = $LAYOUT.byteOffset(groupElement("q_index"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int q_index
     * }
     */
    public static final long q_index$offset() {
        return q_index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int q_index
     * }
     */
    public static int q_index(MemorySegment struct) {
        return struct.get(q_index$LAYOUT, q_index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int q_index
     * }
     */
    public static void q_index(MemorySegment struct, int fieldValue) {
        struct.set(q_index$LAYOUT, q_index$OFFSET, fieldValue);
    }

    private static final OfInt rdmult$LAYOUT = (OfInt)$LAYOUT.select(groupElement("rdmult"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int rdmult
     * }
     */
    public static final OfInt rdmult$layout() {
        return rdmult$LAYOUT;
    }

    private static final long rdmult$OFFSET = $LAYOUT.byteOffset(groupElement("rdmult"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int rdmult
     * }
     */
    public static final long rdmult$offset() {
        return rdmult$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int rdmult
     * }
     */
    public static int rdmult(MemorySegment struct) {
        return struct.get(rdmult$LAYOUT, rdmult$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int rdmult
     * }
     */
    public static void rdmult(MemorySegment struct, int fieldValue) {
        struct.set(rdmult$LAYOUT, rdmult$OFFSET, fieldValue);
    }

    private static final OfInt delta_q_uv$LAYOUT = (OfInt)$LAYOUT.select(groupElement("delta_q_uv"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int delta_q_uv
     * }
     */
    public static final OfInt delta_q_uv$layout() {
        return delta_q_uv$LAYOUT;
    }

    private static final long delta_q_uv$OFFSET = $LAYOUT.byteOffset(groupElement("delta_q_uv"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int delta_q_uv
     * }
     */
    public static final long delta_q_uv$offset() {
        return delta_q_uv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int delta_q_uv
     * }
     */
    public static int delta_q_uv(MemorySegment struct) {
        return struct.get(delta_q_uv$LAYOUT, delta_q_uv$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int delta_q_uv
     * }
     */
    public static void delta_q_uv(MemorySegment struct, int fieldValue) {
        struct.set(delta_q_uv$LAYOUT, delta_q_uv$OFFSET, fieldValue);
    }

    private static final AddressLayout sb_params_list$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("sb_params_list"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * sb_params *sb_params_list
     * }
     */
    public static final AddressLayout sb_params_list$layout() {
        return sb_params_list$LAYOUT;
    }

    private static final long sb_params_list$OFFSET = $LAYOUT.byteOffset(groupElement("sb_params_list"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * sb_params *sb_params_list
     * }
     */
    public static final long sb_params_list$offset() {
        return sb_params_list$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * sb_params *sb_params_list
     * }
     */
    public static MemorySegment sb_params_list(MemorySegment struct) {
        return struct.get(sb_params_list$LAYOUT, sb_params_list$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * sb_params *sb_params_list
     * }
     */
    public static void sb_params_list(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(sb_params_list$LAYOUT, sb_params_list$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

