// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_rc_gop_decision {
 *     int gop_coding_frames;
 *     int use_alt_ref;
 *     int use_key_frame;
 *     vpx_rc_frame_update_type_t update_type[252];
 *     int update_ref_index[252];
 *     vpx_rc_ref_frame_t ref_frame_list[252];
 * } vpx_rc_gop_decision_t
 * }
 */
public class vpx_rc_gop_decision_t extends vpx_rc_gop_decision {

    vpx_rc_gop_decision_t() {
        // Should not be called directly
    }
}

