// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_rc_frame_stats {
 *     double frame;
 *     double weight;
 *     double intra_error;
 *     double coded_error;
 *     double sr_coded_error;
 *     double frame_noise_energy;
 *     double pcnt_inter;
 *     double pcnt_motion;
 *     double pcnt_second_ref;
 *     double pcnt_neutral;
 *     double pcnt_intra_low;
 *     double pcnt_intra_high;
 *     double intra_skip_pct;
 *     double intra_smooth_pct;
 *     double inactive_zone_rows;
 *     double inactive_zone_cols;
 *     double MVr;
 *     double mvr_abs;
 *     double MVc;
 *     double mvc_abs;
 *     double MVrv;
 *     double MVcv;
 *     double mv_in_out_count;
 *     double duration;
 *     double count;
 *     double new_mv_count;
 * }
 * }
 */
public class vpx_rc_frame_stats {

    vpx_rc_frame_stats() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_DOUBLE.withName("frame"),
        VpxFFI.C_DOUBLE.withName("weight"),
        VpxFFI.C_DOUBLE.withName("intra_error"),
        VpxFFI.C_DOUBLE.withName("coded_error"),
        VpxFFI.C_DOUBLE.withName("sr_coded_error"),
        VpxFFI.C_DOUBLE.withName("frame_noise_energy"),
        VpxFFI.C_DOUBLE.withName("pcnt_inter"),
        VpxFFI.C_DOUBLE.withName("pcnt_motion"),
        VpxFFI.C_DOUBLE.withName("pcnt_second_ref"),
        VpxFFI.C_DOUBLE.withName("pcnt_neutral"),
        VpxFFI.C_DOUBLE.withName("pcnt_intra_low"),
        VpxFFI.C_DOUBLE.withName("pcnt_intra_high"),
        VpxFFI.C_DOUBLE.withName("intra_skip_pct"),
        VpxFFI.C_DOUBLE.withName("intra_smooth_pct"),
        VpxFFI.C_DOUBLE.withName("inactive_zone_rows"),
        VpxFFI.C_DOUBLE.withName("inactive_zone_cols"),
        VpxFFI.C_DOUBLE.withName("MVr"),
        VpxFFI.C_DOUBLE.withName("mvr_abs"),
        VpxFFI.C_DOUBLE.withName("MVc"),
        VpxFFI.C_DOUBLE.withName("mvc_abs"),
        VpxFFI.C_DOUBLE.withName("MVrv"),
        VpxFFI.C_DOUBLE.withName("MVcv"),
        VpxFFI.C_DOUBLE.withName("mv_in_out_count"),
        VpxFFI.C_DOUBLE.withName("duration"),
        VpxFFI.C_DOUBLE.withName("count"),
        VpxFFI.C_DOUBLE.withName("new_mv_count")
    ).withName("vpx_rc_frame_stats");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble frame$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("frame"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double frame
     * }
     */
    public static final OfDouble frame$layout() {
        return frame$LAYOUT;
    }

    private static final long frame$OFFSET = $LAYOUT.byteOffset(groupElement("frame"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double frame
     * }
     */
    public static final long frame$offset() {
        return frame$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double frame
     * }
     */
    public static double frame(MemorySegment struct) {
        return struct.get(frame$LAYOUT, frame$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double frame
     * }
     */
    public static void frame(MemorySegment struct, double fieldValue) {
        struct.set(frame$LAYOUT, frame$OFFSET, fieldValue);
    }

    private static final OfDouble weight$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("weight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double weight
     * }
     */
    public static final OfDouble weight$layout() {
        return weight$LAYOUT;
    }

    private static final long weight$OFFSET = $LAYOUT.byteOffset(groupElement("weight"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double weight
     * }
     */
    public static final long weight$offset() {
        return weight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double weight
     * }
     */
    public static double weight(MemorySegment struct) {
        return struct.get(weight$LAYOUT, weight$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double weight
     * }
     */
    public static void weight(MemorySegment struct, double fieldValue) {
        struct.set(weight$LAYOUT, weight$OFFSET, fieldValue);
    }

    private static final OfDouble intra_error$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("intra_error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double intra_error
     * }
     */
    public static final OfDouble intra_error$layout() {
        return intra_error$LAYOUT;
    }

    private static final long intra_error$OFFSET = $LAYOUT.byteOffset(groupElement("intra_error"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double intra_error
     * }
     */
    public static final long intra_error$offset() {
        return intra_error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double intra_error
     * }
     */
    public static double intra_error(MemorySegment struct) {
        return struct.get(intra_error$LAYOUT, intra_error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double intra_error
     * }
     */
    public static void intra_error(MemorySegment struct, double fieldValue) {
        struct.set(intra_error$LAYOUT, intra_error$OFFSET, fieldValue);
    }

    private static final OfDouble coded_error$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("coded_error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double coded_error
     * }
     */
    public static final OfDouble coded_error$layout() {
        return coded_error$LAYOUT;
    }

    private static final long coded_error$OFFSET = $LAYOUT.byteOffset(groupElement("coded_error"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double coded_error
     * }
     */
    public static final long coded_error$offset() {
        return coded_error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double coded_error
     * }
     */
    public static double coded_error(MemorySegment struct) {
        return struct.get(coded_error$LAYOUT, coded_error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double coded_error
     * }
     */
    public static void coded_error(MemorySegment struct, double fieldValue) {
        struct.set(coded_error$LAYOUT, coded_error$OFFSET, fieldValue);
    }

    private static final OfDouble sr_coded_error$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("sr_coded_error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double sr_coded_error
     * }
     */
    public static final OfDouble sr_coded_error$layout() {
        return sr_coded_error$LAYOUT;
    }

    private static final long sr_coded_error$OFFSET = $LAYOUT.byteOffset(groupElement("sr_coded_error"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double sr_coded_error
     * }
     */
    public static final long sr_coded_error$offset() {
        return sr_coded_error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double sr_coded_error
     * }
     */
    public static double sr_coded_error(MemorySegment struct) {
        return struct.get(sr_coded_error$LAYOUT, sr_coded_error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double sr_coded_error
     * }
     */
    public static void sr_coded_error(MemorySegment struct, double fieldValue) {
        struct.set(sr_coded_error$LAYOUT, sr_coded_error$OFFSET, fieldValue);
    }

    private static final OfDouble frame_noise_energy$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("frame_noise_energy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double frame_noise_energy
     * }
     */
    public static final OfDouble frame_noise_energy$layout() {
        return frame_noise_energy$LAYOUT;
    }

    private static final long frame_noise_energy$OFFSET = $LAYOUT.byteOffset(groupElement("frame_noise_energy"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double frame_noise_energy
     * }
     */
    public static final long frame_noise_energy$offset() {
        return frame_noise_energy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double frame_noise_energy
     * }
     */
    public static double frame_noise_energy(MemorySegment struct) {
        return struct.get(frame_noise_energy$LAYOUT, frame_noise_energy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double frame_noise_energy
     * }
     */
    public static void frame_noise_energy(MemorySegment struct, double fieldValue) {
        struct.set(frame_noise_energy$LAYOUT, frame_noise_energy$OFFSET, fieldValue);
    }

    private static final OfDouble pcnt_inter$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("pcnt_inter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double pcnt_inter
     * }
     */
    public static final OfDouble pcnt_inter$layout() {
        return pcnt_inter$LAYOUT;
    }

    private static final long pcnt_inter$OFFSET = $LAYOUT.byteOffset(groupElement("pcnt_inter"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double pcnt_inter
     * }
     */
    public static final long pcnt_inter$offset() {
        return pcnt_inter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double pcnt_inter
     * }
     */
    public static double pcnt_inter(MemorySegment struct) {
        return struct.get(pcnt_inter$LAYOUT, pcnt_inter$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double pcnt_inter
     * }
     */
    public static void pcnt_inter(MemorySegment struct, double fieldValue) {
        struct.set(pcnt_inter$LAYOUT, pcnt_inter$OFFSET, fieldValue);
    }

    private static final OfDouble pcnt_motion$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("pcnt_motion"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double pcnt_motion
     * }
     */
    public static final OfDouble pcnt_motion$layout() {
        return pcnt_motion$LAYOUT;
    }

    private static final long pcnt_motion$OFFSET = $LAYOUT.byteOffset(groupElement("pcnt_motion"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double pcnt_motion
     * }
     */
    public static final long pcnt_motion$offset() {
        return pcnt_motion$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double pcnt_motion
     * }
     */
    public static double pcnt_motion(MemorySegment struct) {
        return struct.get(pcnt_motion$LAYOUT, pcnt_motion$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double pcnt_motion
     * }
     */
    public static void pcnt_motion(MemorySegment struct, double fieldValue) {
        struct.set(pcnt_motion$LAYOUT, pcnt_motion$OFFSET, fieldValue);
    }

    private static final OfDouble pcnt_second_ref$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("pcnt_second_ref"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double pcnt_second_ref
     * }
     */
    public static final OfDouble pcnt_second_ref$layout() {
        return pcnt_second_ref$LAYOUT;
    }

    private static final long pcnt_second_ref$OFFSET = $LAYOUT.byteOffset(groupElement("pcnt_second_ref"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double pcnt_second_ref
     * }
     */
    public static final long pcnt_second_ref$offset() {
        return pcnt_second_ref$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double pcnt_second_ref
     * }
     */
    public static double pcnt_second_ref(MemorySegment struct) {
        return struct.get(pcnt_second_ref$LAYOUT, pcnt_second_ref$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double pcnt_second_ref
     * }
     */
    public static void pcnt_second_ref(MemorySegment struct, double fieldValue) {
        struct.set(pcnt_second_ref$LAYOUT, pcnt_second_ref$OFFSET, fieldValue);
    }

    private static final OfDouble pcnt_neutral$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("pcnt_neutral"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double pcnt_neutral
     * }
     */
    public static final OfDouble pcnt_neutral$layout() {
        return pcnt_neutral$LAYOUT;
    }

    private static final long pcnt_neutral$OFFSET = $LAYOUT.byteOffset(groupElement("pcnt_neutral"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double pcnt_neutral
     * }
     */
    public static final long pcnt_neutral$offset() {
        return pcnt_neutral$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double pcnt_neutral
     * }
     */
    public static double pcnt_neutral(MemorySegment struct) {
        return struct.get(pcnt_neutral$LAYOUT, pcnt_neutral$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double pcnt_neutral
     * }
     */
    public static void pcnt_neutral(MemorySegment struct, double fieldValue) {
        struct.set(pcnt_neutral$LAYOUT, pcnt_neutral$OFFSET, fieldValue);
    }

    private static final OfDouble pcnt_intra_low$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("pcnt_intra_low"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double pcnt_intra_low
     * }
     */
    public static final OfDouble pcnt_intra_low$layout() {
        return pcnt_intra_low$LAYOUT;
    }

    private static final long pcnt_intra_low$OFFSET = $LAYOUT.byteOffset(groupElement("pcnt_intra_low"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double pcnt_intra_low
     * }
     */
    public static final long pcnt_intra_low$offset() {
        return pcnt_intra_low$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double pcnt_intra_low
     * }
     */
    public static double pcnt_intra_low(MemorySegment struct) {
        return struct.get(pcnt_intra_low$LAYOUT, pcnt_intra_low$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double pcnt_intra_low
     * }
     */
    public static void pcnt_intra_low(MemorySegment struct, double fieldValue) {
        struct.set(pcnt_intra_low$LAYOUT, pcnt_intra_low$OFFSET, fieldValue);
    }

    private static final OfDouble pcnt_intra_high$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("pcnt_intra_high"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double pcnt_intra_high
     * }
     */
    public static final OfDouble pcnt_intra_high$layout() {
        return pcnt_intra_high$LAYOUT;
    }

    private static final long pcnt_intra_high$OFFSET = $LAYOUT.byteOffset(groupElement("pcnt_intra_high"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double pcnt_intra_high
     * }
     */
    public static final long pcnt_intra_high$offset() {
        return pcnt_intra_high$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double pcnt_intra_high
     * }
     */
    public static double pcnt_intra_high(MemorySegment struct) {
        return struct.get(pcnt_intra_high$LAYOUT, pcnt_intra_high$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double pcnt_intra_high
     * }
     */
    public static void pcnt_intra_high(MemorySegment struct, double fieldValue) {
        struct.set(pcnt_intra_high$LAYOUT, pcnt_intra_high$OFFSET, fieldValue);
    }

    private static final OfDouble intra_skip_pct$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("intra_skip_pct"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double intra_skip_pct
     * }
     */
    public static final OfDouble intra_skip_pct$layout() {
        return intra_skip_pct$LAYOUT;
    }

    private static final long intra_skip_pct$OFFSET = $LAYOUT.byteOffset(groupElement("intra_skip_pct"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double intra_skip_pct
     * }
     */
    public static final long intra_skip_pct$offset() {
        return intra_skip_pct$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double intra_skip_pct
     * }
     */
    public static double intra_skip_pct(MemorySegment struct) {
        return struct.get(intra_skip_pct$LAYOUT, intra_skip_pct$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double intra_skip_pct
     * }
     */
    public static void intra_skip_pct(MemorySegment struct, double fieldValue) {
        struct.set(intra_skip_pct$LAYOUT, intra_skip_pct$OFFSET, fieldValue);
    }

    private static final OfDouble intra_smooth_pct$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("intra_smooth_pct"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double intra_smooth_pct
     * }
     */
    public static final OfDouble intra_smooth_pct$layout() {
        return intra_smooth_pct$LAYOUT;
    }

    private static final long intra_smooth_pct$OFFSET = $LAYOUT.byteOffset(groupElement("intra_smooth_pct"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double intra_smooth_pct
     * }
     */
    public static final long intra_smooth_pct$offset() {
        return intra_smooth_pct$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double intra_smooth_pct
     * }
     */
    public static double intra_smooth_pct(MemorySegment struct) {
        return struct.get(intra_smooth_pct$LAYOUT, intra_smooth_pct$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double intra_smooth_pct
     * }
     */
    public static void intra_smooth_pct(MemorySegment struct, double fieldValue) {
        struct.set(intra_smooth_pct$LAYOUT, intra_smooth_pct$OFFSET, fieldValue);
    }

    private static final OfDouble inactive_zone_rows$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("inactive_zone_rows"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double inactive_zone_rows
     * }
     */
    public static final OfDouble inactive_zone_rows$layout() {
        return inactive_zone_rows$LAYOUT;
    }

    private static final long inactive_zone_rows$OFFSET = $LAYOUT.byteOffset(groupElement("inactive_zone_rows"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double inactive_zone_rows
     * }
     */
    public static final long inactive_zone_rows$offset() {
        return inactive_zone_rows$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double inactive_zone_rows
     * }
     */
    public static double inactive_zone_rows(MemorySegment struct) {
        return struct.get(inactive_zone_rows$LAYOUT, inactive_zone_rows$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double inactive_zone_rows
     * }
     */
    public static void inactive_zone_rows(MemorySegment struct, double fieldValue) {
        struct.set(inactive_zone_rows$LAYOUT, inactive_zone_rows$OFFSET, fieldValue);
    }

    private static final OfDouble inactive_zone_cols$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("inactive_zone_cols"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double inactive_zone_cols
     * }
     */
    public static final OfDouble inactive_zone_cols$layout() {
        return inactive_zone_cols$LAYOUT;
    }

    private static final long inactive_zone_cols$OFFSET = $LAYOUT.byteOffset(groupElement("inactive_zone_cols"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double inactive_zone_cols
     * }
     */
    public static final long inactive_zone_cols$offset() {
        return inactive_zone_cols$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double inactive_zone_cols
     * }
     */
    public static double inactive_zone_cols(MemorySegment struct) {
        return struct.get(inactive_zone_cols$LAYOUT, inactive_zone_cols$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double inactive_zone_cols
     * }
     */
    public static void inactive_zone_cols(MemorySegment struct, double fieldValue) {
        struct.set(inactive_zone_cols$LAYOUT, inactive_zone_cols$OFFSET, fieldValue);
    }

    private static final OfDouble MVr$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("MVr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double MVr
     * }
     */
    public static final OfDouble MVr$layout() {
        return MVr$LAYOUT;
    }

    private static final long MVr$OFFSET = $LAYOUT.byteOffset(groupElement("MVr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double MVr
     * }
     */
    public static final long MVr$offset() {
        return MVr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double MVr
     * }
     */
    public static double MVr(MemorySegment struct) {
        return struct.get(MVr$LAYOUT, MVr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double MVr
     * }
     */
    public static void MVr(MemorySegment struct, double fieldValue) {
        struct.set(MVr$LAYOUT, MVr$OFFSET, fieldValue);
    }

    private static final OfDouble mvr_abs$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("mvr_abs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double mvr_abs
     * }
     */
    public static final OfDouble mvr_abs$layout() {
        return mvr_abs$LAYOUT;
    }

    private static final long mvr_abs$OFFSET = $LAYOUT.byteOffset(groupElement("mvr_abs"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double mvr_abs
     * }
     */
    public static final long mvr_abs$offset() {
        return mvr_abs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double mvr_abs
     * }
     */
    public static double mvr_abs(MemorySegment struct) {
        return struct.get(mvr_abs$LAYOUT, mvr_abs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double mvr_abs
     * }
     */
    public static void mvr_abs(MemorySegment struct, double fieldValue) {
        struct.set(mvr_abs$LAYOUT, mvr_abs$OFFSET, fieldValue);
    }

    private static final OfDouble MVc$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("MVc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double MVc
     * }
     */
    public static final OfDouble MVc$layout() {
        return MVc$LAYOUT;
    }

    private static final long MVc$OFFSET = $LAYOUT.byteOffset(groupElement("MVc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double MVc
     * }
     */
    public static final long MVc$offset() {
        return MVc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double MVc
     * }
     */
    public static double MVc(MemorySegment struct) {
        return struct.get(MVc$LAYOUT, MVc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double MVc
     * }
     */
    public static void MVc(MemorySegment struct, double fieldValue) {
        struct.set(MVc$LAYOUT, MVc$OFFSET, fieldValue);
    }

    private static final OfDouble mvc_abs$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("mvc_abs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double mvc_abs
     * }
     */
    public static final OfDouble mvc_abs$layout() {
        return mvc_abs$LAYOUT;
    }

    private static final long mvc_abs$OFFSET = $LAYOUT.byteOffset(groupElement("mvc_abs"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double mvc_abs
     * }
     */
    public static final long mvc_abs$offset() {
        return mvc_abs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double mvc_abs
     * }
     */
    public static double mvc_abs(MemorySegment struct) {
        return struct.get(mvc_abs$LAYOUT, mvc_abs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double mvc_abs
     * }
     */
    public static void mvc_abs(MemorySegment struct, double fieldValue) {
        struct.set(mvc_abs$LAYOUT, mvc_abs$OFFSET, fieldValue);
    }

    private static final OfDouble MVrv$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("MVrv"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double MVrv
     * }
     */
    public static final OfDouble MVrv$layout() {
        return MVrv$LAYOUT;
    }

    private static final long MVrv$OFFSET = $LAYOUT.byteOffset(groupElement("MVrv"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double MVrv
     * }
     */
    public static final long MVrv$offset() {
        return MVrv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double MVrv
     * }
     */
    public static double MVrv(MemorySegment struct) {
        return struct.get(MVrv$LAYOUT, MVrv$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double MVrv
     * }
     */
    public static void MVrv(MemorySegment struct, double fieldValue) {
        struct.set(MVrv$LAYOUT, MVrv$OFFSET, fieldValue);
    }

    private static final OfDouble MVcv$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("MVcv"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double MVcv
     * }
     */
    public static final OfDouble MVcv$layout() {
        return MVcv$LAYOUT;
    }

    private static final long MVcv$OFFSET = $LAYOUT.byteOffset(groupElement("MVcv"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double MVcv
     * }
     */
    public static final long MVcv$offset() {
        return MVcv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double MVcv
     * }
     */
    public static double MVcv(MemorySegment struct) {
        return struct.get(MVcv$LAYOUT, MVcv$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double MVcv
     * }
     */
    public static void MVcv(MemorySegment struct, double fieldValue) {
        struct.set(MVcv$LAYOUT, MVcv$OFFSET, fieldValue);
    }

    private static final OfDouble mv_in_out_count$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("mv_in_out_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double mv_in_out_count
     * }
     */
    public static final OfDouble mv_in_out_count$layout() {
        return mv_in_out_count$LAYOUT;
    }

    private static final long mv_in_out_count$OFFSET = $LAYOUT.byteOffset(groupElement("mv_in_out_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double mv_in_out_count
     * }
     */
    public static final long mv_in_out_count$offset() {
        return mv_in_out_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double mv_in_out_count
     * }
     */
    public static double mv_in_out_count(MemorySegment struct) {
        return struct.get(mv_in_out_count$LAYOUT, mv_in_out_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double mv_in_out_count
     * }
     */
    public static void mv_in_out_count(MemorySegment struct, double fieldValue) {
        struct.set(mv_in_out_count$LAYOUT, mv_in_out_count$OFFSET, fieldValue);
    }

    private static final OfDouble duration$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("duration"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double duration
     * }
     */
    public static final OfDouble duration$layout() {
        return duration$LAYOUT;
    }

    private static final long duration$OFFSET = $LAYOUT.byteOffset(groupElement("duration"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double duration
     * }
     */
    public static final long duration$offset() {
        return duration$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double duration
     * }
     */
    public static double duration(MemorySegment struct) {
        return struct.get(duration$LAYOUT, duration$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double duration
     * }
     */
    public static void duration(MemorySegment struct, double fieldValue) {
        struct.set(duration$LAYOUT, duration$OFFSET, fieldValue);
    }

    private static final OfDouble count$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double count
     * }
     */
    public static final OfDouble count$layout() {
        return count$LAYOUT;
    }

    private static final long count$OFFSET = $LAYOUT.byteOffset(groupElement("count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double count
     * }
     */
    public static final long count$offset() {
        return count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double count
     * }
     */
    public static double count(MemorySegment struct) {
        return struct.get(count$LAYOUT, count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double count
     * }
     */
    public static void count(MemorySegment struct, double fieldValue) {
        struct.set(count$LAYOUT, count$OFFSET, fieldValue);
    }

    private static final OfDouble new_mv_count$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("new_mv_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double new_mv_count
     * }
     */
    public static final OfDouble new_mv_count$layout() {
        return new_mv_count$LAYOUT;
    }

    private static final long new_mv_count$OFFSET = $LAYOUT.byteOffset(groupElement("new_mv_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double new_mv_count
     * }
     */
    public static final long new_mv_count$offset() {
        return new_mv_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double new_mv_count
     * }
     */
    public static double new_mv_count(MemorySegment struct) {
        return struct.get(new_mv_count$LAYOUT, new_mv_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double new_mv_count
     * }
     */
    public static void new_mv_count(MemorySegment struct, double fieldValue) {
        struct.set(new_mv_count$LAYOUT, new_mv_count$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

