// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_scaling_mode {
 *     VPX_SCALING_MODE h_scaling_mode;
 *     VPX_SCALING_MODE v_scaling_mode;
 * }
 * }
 */
public class vpx_scaling_mode$0 {

    vpx_scaling_mode$0() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_INT.withName("h_scaling_mode"),
        VpxFFI.C_INT.withName("v_scaling_mode")
    ).withName("vpx_scaling_mode");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt h_scaling_mode$LAYOUT = (OfInt)$LAYOUT.select(groupElement("h_scaling_mode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VPX_SCALING_MODE h_scaling_mode
     * }
     */
    public static final OfInt h_scaling_mode$layout() {
        return h_scaling_mode$LAYOUT;
    }

    private static final long h_scaling_mode$OFFSET = $LAYOUT.byteOffset(groupElement("h_scaling_mode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VPX_SCALING_MODE h_scaling_mode
     * }
     */
    public static final long h_scaling_mode$offset() {
        return h_scaling_mode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VPX_SCALING_MODE h_scaling_mode
     * }
     */
    public static int h_scaling_mode(MemorySegment struct) {
        return struct.get(h_scaling_mode$LAYOUT, h_scaling_mode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VPX_SCALING_MODE h_scaling_mode
     * }
     */
    public static void h_scaling_mode(MemorySegment struct, int fieldValue) {
        struct.set(h_scaling_mode$LAYOUT, h_scaling_mode$OFFSET, fieldValue);
    }

    private static final OfInt v_scaling_mode$LAYOUT = (OfInt)$LAYOUT.select(groupElement("v_scaling_mode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VPX_SCALING_MODE v_scaling_mode
     * }
     */
    public static final OfInt v_scaling_mode$layout() {
        return v_scaling_mode$LAYOUT;
    }

    private static final long v_scaling_mode$OFFSET = $LAYOUT.byteOffset(groupElement("v_scaling_mode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VPX_SCALING_MODE v_scaling_mode
     * }
     */
    public static final long v_scaling_mode$offset() {
        return v_scaling_mode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VPX_SCALING_MODE v_scaling_mode
     * }
     */
    public static int v_scaling_mode(MemorySegment struct) {
        return struct.get(v_scaling_mode$LAYOUT, v_scaling_mode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VPX_SCALING_MODE v_scaling_mode
     * }
     */
    public static void v_scaling_mode(MemorySegment struct, int fieldValue) {
        struct.set(v_scaling_mode$LAYOUT, v_scaling_mode$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

