// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_codec_enc_cfg {
 *     unsigned int g_usage;
 *     unsigned int g_threads;
 *     unsigned int g_profile;
 *     unsigned int g_w;
 *     unsigned int g_h;
 *     vpx_bit_depth_t g_bit_depth;
 *     unsigned int g_input_bit_depth;
 *     struct vpx_rational g_timebase;
 *     vpx_codec_er_flags_t g_error_resilient;
 *     enum vpx_enc_pass g_pass;
 *     unsigned int g_lag_in_frames;
 *     unsigned int rc_dropframe_thresh;
 *     unsigned int rc_resize_allowed;
 *     unsigned int rc_scaled_width;
 *     unsigned int rc_scaled_height;
 *     unsigned int rc_resize_up_thresh;
 *     unsigned int rc_resize_down_thresh;
 *     enum vpx_rc_mode rc_end_usage;
 *     vpx_fixed_buf_t rc_twopass_stats_in;
 *     vpx_fixed_buf_t rc_firstpass_mb_stats_in;
 *     unsigned int rc_target_bitrate;
 *     unsigned int rc_min_quantizer;
 *     unsigned int rc_max_quantizer;
 *     unsigned int rc_undershoot_pct;
 *     unsigned int rc_overshoot_pct;
 *     unsigned int rc_buf_sz;
 *     unsigned int rc_buf_initial_sz;
 *     unsigned int rc_buf_optimal_sz;
 *     unsigned int rc_2pass_vbr_bias_pct;
 *     unsigned int rc_2pass_vbr_minsection_pct;
 *     unsigned int rc_2pass_vbr_maxsection_pct;
 *     unsigned int rc_2pass_vbr_corpus_complexity;
 *     enum vpx_kf_mode kf_mode;
 *     unsigned int kf_min_dist;
 *     unsigned int kf_max_dist;
 *     unsigned int ss_number_layers;
 *     int ss_enable_auto_alt_ref[5];
 *     unsigned int ss_target_bitrate[5];
 *     unsigned int ts_number_layers;
 *     unsigned int ts_target_bitrate[5];
 *     unsigned int ts_rate_decimator[5];
 *     unsigned int ts_periodicity;
 *     unsigned int ts_layer_id[16];
 *     unsigned int layer_target_bitrate[12];
 *     int temporal_layering_mode;
 *     int use_vizier_rc_params;
 *     vpx_rational_t active_wq_factor;
 *     vpx_rational_t err_per_mb_factor;
 *     vpx_rational_t sr_default_decay_limit;
 *     vpx_rational_t sr_diff_factor;
 *     vpx_rational_t kf_err_per_mb_factor;
 *     vpx_rational_t kf_frame_min_boost_factor;
 *     vpx_rational_t kf_frame_max_boost_first_factor;
 *     vpx_rational_t kf_frame_max_boost_subs_factor;
 *     vpx_rational_t kf_max_total_boost_factor;
 *     vpx_rational_t gf_max_total_boost_factor;
 *     vpx_rational_t gf_frame_max_boost_factor;
 *     vpx_rational_t zm_factor;
 *     vpx_rational_t rd_mult_inter_qp_fac;
 *     vpx_rational_t rd_mult_arf_qp_fac;
 *     vpx_rational_t rd_mult_key_qp_fac;
 * } vpx_codec_enc_cfg_t
 * }
 */
public class vpx_codec_enc_cfg_t extends vpx_codec_enc_cfg {

    vpx_codec_enc_cfg_t() {
        // Should not be called directly
    }
}

