// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_rc_ref_frame {
 *     int index[4];
 *     vpx_rc_ref_name_t name[4];
 * } vpx_rc_ref_frame_t
 * }
 */
public class vpx_rc_ref_frame_t extends vpx_rc_ref_frame {

    vpx_rc_ref_frame_t() {
        // Should not be called directly
    }
}

