// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_svc_spatial_layer_sync {
 *     int spatial_layer_sync[5];
 *     int base_layer_intra_only;
 * } vpx_svc_spatial_layer_sync_t
 * }
 */
public class vpx_svc_spatial_layer_sync_t extends vpx_svc_spatial_layer_sync {

    vpx_svc_spatial_layer_sync_t() {
        // Should not be called directly
    }
}

