// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_rc_funcs {
 *     vpx_rc_type_t rc_type;
 *     vpx_rc_create_model_cb_fn_t create_model;
 *     vpx_rc_send_firstpass_stats_cb_fn_t send_firstpass_stats;
 *     vpx_rc_send_tpl_gop_stats_cb_fn_t send_tpl_gop_stats;
 *     vpx_rc_get_encodeframe_decision_cb_fn_t get_encodeframe_decision;
 *     vpx_rc_update_encodeframe_result_cb_fn_t update_encodeframe_result;
 *     vpx_rc_get_key_frame_decision_cb_fn_t get_key_frame_decision;
 *     vpx_rc_get_gop_decision_cb_fn_t get_gop_decision;
 *     vpx_rc_get_frame_rdmult_cb_fn_t get_frame_rdmult;
 *     vpx_rc_delete_model_cb_fn_t delete_model;
 *     const char *rate_ctrl_log_path;
 *     void *priv;
 * }
 * }
 */
public class vpx_rc_funcs {

    vpx_rc_funcs() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_INT.withName("rc_type"),
        MemoryLayout.paddingLayout(4),
        VpxFFI.C_POINTER.withName("create_model"),
        VpxFFI.C_POINTER.withName("send_firstpass_stats"),
        VpxFFI.C_POINTER.withName("send_tpl_gop_stats"),
        VpxFFI.C_POINTER.withName("get_encodeframe_decision"),
        VpxFFI.C_POINTER.withName("update_encodeframe_result"),
        VpxFFI.C_POINTER.withName("get_key_frame_decision"),
        VpxFFI.C_POINTER.withName("get_gop_decision"),
        VpxFFI.C_POINTER.withName("get_frame_rdmult"),
        VpxFFI.C_POINTER.withName("delete_model"),
        VpxFFI.C_POINTER.withName("rate_ctrl_log_path"),
        VpxFFI.C_POINTER.withName("priv")
    ).withName("vpx_rc_funcs");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt rc_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("rc_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_rc_type_t rc_type
     * }
     */
    public static final OfInt rc_type$layout() {
        return rc_type$LAYOUT;
    }

    private static final long rc_type$OFFSET = $LAYOUT.byteOffset(groupElement("rc_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_rc_type_t rc_type
     * }
     */
    public static final long rc_type$offset() {
        return rc_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_rc_type_t rc_type
     * }
     */
    public static int rc_type(MemorySegment struct) {
        return struct.get(rc_type$LAYOUT, rc_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_rc_type_t rc_type
     * }
     */
    public static void rc_type(MemorySegment struct, int fieldValue) {
        struct.set(rc_type$LAYOUT, rc_type$OFFSET, fieldValue);
    }

    private static final AddressLayout create_model$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("create_model"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_rc_create_model_cb_fn_t create_model
     * }
     */
    public static final AddressLayout create_model$layout() {
        return create_model$LAYOUT;
    }

    private static final long create_model$OFFSET = $LAYOUT.byteOffset(groupElement("create_model"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_rc_create_model_cb_fn_t create_model
     * }
     */
    public static final long create_model$offset() {
        return create_model$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_rc_create_model_cb_fn_t create_model
     * }
     */
    public static MemorySegment create_model(MemorySegment struct) {
        return struct.get(create_model$LAYOUT, create_model$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_rc_create_model_cb_fn_t create_model
     * }
     */
    public static void create_model(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(create_model$LAYOUT, create_model$OFFSET, fieldValue);
    }

    private static final AddressLayout send_firstpass_stats$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("send_firstpass_stats"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_rc_send_firstpass_stats_cb_fn_t send_firstpass_stats
     * }
     */
    public static final AddressLayout send_firstpass_stats$layout() {
        return send_firstpass_stats$LAYOUT;
    }

    private static final long send_firstpass_stats$OFFSET = $LAYOUT.byteOffset(groupElement("send_firstpass_stats"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_rc_send_firstpass_stats_cb_fn_t send_firstpass_stats
     * }
     */
    public static final long send_firstpass_stats$offset() {
        return send_firstpass_stats$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_rc_send_firstpass_stats_cb_fn_t send_firstpass_stats
     * }
     */
    public static MemorySegment send_firstpass_stats(MemorySegment struct) {
        return struct.get(send_firstpass_stats$LAYOUT, send_firstpass_stats$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_rc_send_firstpass_stats_cb_fn_t send_firstpass_stats
     * }
     */
    public static void send_firstpass_stats(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(send_firstpass_stats$LAYOUT, send_firstpass_stats$OFFSET, fieldValue);
    }

    private static final AddressLayout send_tpl_gop_stats$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("send_tpl_gop_stats"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_rc_send_tpl_gop_stats_cb_fn_t send_tpl_gop_stats
     * }
     */
    public static final AddressLayout send_tpl_gop_stats$layout() {
        return send_tpl_gop_stats$LAYOUT;
    }

    private static final long send_tpl_gop_stats$OFFSET = $LAYOUT.byteOffset(groupElement("send_tpl_gop_stats"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_rc_send_tpl_gop_stats_cb_fn_t send_tpl_gop_stats
     * }
     */
    public static final long send_tpl_gop_stats$offset() {
        return send_tpl_gop_stats$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_rc_send_tpl_gop_stats_cb_fn_t send_tpl_gop_stats
     * }
     */
    public static MemorySegment send_tpl_gop_stats(MemorySegment struct) {
        return struct.get(send_tpl_gop_stats$LAYOUT, send_tpl_gop_stats$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_rc_send_tpl_gop_stats_cb_fn_t send_tpl_gop_stats
     * }
     */
    public static void send_tpl_gop_stats(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(send_tpl_gop_stats$LAYOUT, send_tpl_gop_stats$OFFSET, fieldValue);
    }

    private static final AddressLayout get_encodeframe_decision$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_encodeframe_decision"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_rc_get_encodeframe_decision_cb_fn_t get_encodeframe_decision
     * }
     */
    public static final AddressLayout get_encodeframe_decision$layout() {
        return get_encodeframe_decision$LAYOUT;
    }

    private static final long get_encodeframe_decision$OFFSET = $LAYOUT.byteOffset(groupElement("get_encodeframe_decision"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_rc_get_encodeframe_decision_cb_fn_t get_encodeframe_decision
     * }
     */
    public static final long get_encodeframe_decision$offset() {
        return get_encodeframe_decision$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_rc_get_encodeframe_decision_cb_fn_t get_encodeframe_decision
     * }
     */
    public static MemorySegment get_encodeframe_decision(MemorySegment struct) {
        return struct.get(get_encodeframe_decision$LAYOUT, get_encodeframe_decision$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_rc_get_encodeframe_decision_cb_fn_t get_encodeframe_decision
     * }
     */
    public static void get_encodeframe_decision(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_encodeframe_decision$LAYOUT, get_encodeframe_decision$OFFSET, fieldValue);
    }

    private static final AddressLayout update_encodeframe_result$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("update_encodeframe_result"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_rc_update_encodeframe_result_cb_fn_t update_encodeframe_result
     * }
     */
    public static final AddressLayout update_encodeframe_result$layout() {
        return update_encodeframe_result$LAYOUT;
    }

    private static final long update_encodeframe_result$OFFSET = $LAYOUT.byteOffset(groupElement("update_encodeframe_result"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_rc_update_encodeframe_result_cb_fn_t update_encodeframe_result
     * }
     */
    public static final long update_encodeframe_result$offset() {
        return update_encodeframe_result$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_rc_update_encodeframe_result_cb_fn_t update_encodeframe_result
     * }
     */
    public static MemorySegment update_encodeframe_result(MemorySegment struct) {
        return struct.get(update_encodeframe_result$LAYOUT, update_encodeframe_result$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_rc_update_encodeframe_result_cb_fn_t update_encodeframe_result
     * }
     */
    public static void update_encodeframe_result(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(update_encodeframe_result$LAYOUT, update_encodeframe_result$OFFSET, fieldValue);
    }

    private static final AddressLayout get_key_frame_decision$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_key_frame_decision"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_rc_get_key_frame_decision_cb_fn_t get_key_frame_decision
     * }
     */
    public static final AddressLayout get_key_frame_decision$layout() {
        return get_key_frame_decision$LAYOUT;
    }

    private static final long get_key_frame_decision$OFFSET = $LAYOUT.byteOffset(groupElement("get_key_frame_decision"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_rc_get_key_frame_decision_cb_fn_t get_key_frame_decision
     * }
     */
    public static final long get_key_frame_decision$offset() {
        return get_key_frame_decision$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_rc_get_key_frame_decision_cb_fn_t get_key_frame_decision
     * }
     */
    public static MemorySegment get_key_frame_decision(MemorySegment struct) {
        return struct.get(get_key_frame_decision$LAYOUT, get_key_frame_decision$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_rc_get_key_frame_decision_cb_fn_t get_key_frame_decision
     * }
     */
    public static void get_key_frame_decision(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_key_frame_decision$LAYOUT, get_key_frame_decision$OFFSET, fieldValue);
    }

    private static final AddressLayout get_gop_decision$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_gop_decision"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_rc_get_gop_decision_cb_fn_t get_gop_decision
     * }
     */
    public static final AddressLayout get_gop_decision$layout() {
        return get_gop_decision$LAYOUT;
    }

    private static final long get_gop_decision$OFFSET = $LAYOUT.byteOffset(groupElement("get_gop_decision"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_rc_get_gop_decision_cb_fn_t get_gop_decision
     * }
     */
    public static final long get_gop_decision$offset() {
        return get_gop_decision$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_rc_get_gop_decision_cb_fn_t get_gop_decision
     * }
     */
    public static MemorySegment get_gop_decision(MemorySegment struct) {
        return struct.get(get_gop_decision$LAYOUT, get_gop_decision$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_rc_get_gop_decision_cb_fn_t get_gop_decision
     * }
     */
    public static void get_gop_decision(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_gop_decision$LAYOUT, get_gop_decision$OFFSET, fieldValue);
    }

    private static final AddressLayout get_frame_rdmult$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_frame_rdmult"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_rc_get_frame_rdmult_cb_fn_t get_frame_rdmult
     * }
     */
    public static final AddressLayout get_frame_rdmult$layout() {
        return get_frame_rdmult$LAYOUT;
    }

    private static final long get_frame_rdmult$OFFSET = $LAYOUT.byteOffset(groupElement("get_frame_rdmult"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_rc_get_frame_rdmult_cb_fn_t get_frame_rdmult
     * }
     */
    public static final long get_frame_rdmult$offset() {
        return get_frame_rdmult$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_rc_get_frame_rdmult_cb_fn_t get_frame_rdmult
     * }
     */
    public static MemorySegment get_frame_rdmult(MemorySegment struct) {
        return struct.get(get_frame_rdmult$LAYOUT, get_frame_rdmult$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_rc_get_frame_rdmult_cb_fn_t get_frame_rdmult
     * }
     */
    public static void get_frame_rdmult(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_frame_rdmult$LAYOUT, get_frame_rdmult$OFFSET, fieldValue);
    }

    private static final AddressLayout delete_model$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("delete_model"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_rc_delete_model_cb_fn_t delete_model
     * }
     */
    public static final AddressLayout delete_model$layout() {
        return delete_model$LAYOUT;
    }

    private static final long delete_model$OFFSET = $LAYOUT.byteOffset(groupElement("delete_model"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_rc_delete_model_cb_fn_t delete_model
     * }
     */
    public static final long delete_model$offset() {
        return delete_model$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_rc_delete_model_cb_fn_t delete_model
     * }
     */
    public static MemorySegment delete_model(MemorySegment struct) {
        return struct.get(delete_model$LAYOUT, delete_model$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_rc_delete_model_cb_fn_t delete_model
     * }
     */
    public static void delete_model(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(delete_model$LAYOUT, delete_model$OFFSET, fieldValue);
    }

    private static final AddressLayout rate_ctrl_log_path$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("rate_ctrl_log_path"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *rate_ctrl_log_path
     * }
     */
    public static final AddressLayout rate_ctrl_log_path$layout() {
        return rate_ctrl_log_path$LAYOUT;
    }

    private static final long rate_ctrl_log_path$OFFSET = $LAYOUT.byteOffset(groupElement("rate_ctrl_log_path"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *rate_ctrl_log_path
     * }
     */
    public static final long rate_ctrl_log_path$offset() {
        return rate_ctrl_log_path$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *rate_ctrl_log_path
     * }
     */
    public static MemorySegment rate_ctrl_log_path(MemorySegment struct) {
        return struct.get(rate_ctrl_log_path$LAYOUT, rate_ctrl_log_path$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *rate_ctrl_log_path
     * }
     */
    public static void rate_ctrl_log_path(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(rate_ctrl_log_path$LAYOUT, rate_ctrl_log_path$OFFSET, fieldValue);
    }

    private static final AddressLayout priv$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("priv"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *priv
     * }
     */
    public static final AddressLayout priv$layout() {
        return priv$LAYOUT;
    }

    private static final long priv$OFFSET = $LAYOUT.byteOffset(groupElement("priv"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *priv
     * }
     */
    public static final long priv$offset() {
        return priv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *priv
     * }
     */
    public static MemorySegment priv(MemorySegment struct) {
        return struct.get(priv$LAYOUT, priv$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *priv
     * }
     */
    public static void priv(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(priv$LAYOUT, priv$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

