// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_rc_config {
 *     int frame_width;
 *     int frame_height;
 *     int show_frame_count;
 *     int max_gf_interval;
 *     int min_gf_interval;
 *     int target_bitrate_kbps;
 *     int frame_rate_num;
 *     int frame_rate_den;
 *     vpx_ext_rc_mode_t rc_mode;
 *     int overshoot_percent;
 *     int undershoot_percent;
 *     int min_base_q_index;
 *     int max_base_q_index;
 *     int base_qp;
 * } vpx_rc_config_t
 * }
 */
public class vpx_rc_config_t extends vpx_rc_config {

    vpx_rc_config_t() {
        // Should not be called directly
    }
}

