// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_roi_map {
 *     uint8_t enabled;
 *     unsigned char *roi_map;
 *     unsigned int rows;
 *     unsigned int cols;
 *     int delta_q[8];
 *     int delta_lf[8];
 *     int skip[8];
 *     int ref_frame[8];
 *     unsigned int static_threshold[4];
 * } vpx_roi_map_t
 * }
 */
public class vpx_roi_map_t extends vpx_roi_map {

    vpx_roi_map_t() {
        // Should not be called directly
    }
}

