// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_svc_frame_drop {
 *     int framedrop_thresh[5];
 *     SVC_LAYER_DROP_MODE framedrop_mode;
 *     int max_consec_drop;
 * }
 * }
 */
public class vpx_svc_frame_drop {

    vpx_svc_frame_drop() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(5, VpxFFI.C_INT).withName("framedrop_thresh"),
        VpxFFI.C_INT.withName("framedrop_mode"),
        VpxFFI.C_INT.withName("max_consec_drop")
    ).withName("vpx_svc_frame_drop");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout framedrop_thresh$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("framedrop_thresh"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int framedrop_thresh[5]
     * }
     */
    public static final SequenceLayout framedrop_thresh$layout() {
        return framedrop_thresh$LAYOUT;
    }

    private static final long framedrop_thresh$OFFSET = $LAYOUT.byteOffset(groupElement("framedrop_thresh"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int framedrop_thresh[5]
     * }
     */
    public static final long framedrop_thresh$offset() {
        return framedrop_thresh$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int framedrop_thresh[5]
     * }
     */
    public static MemorySegment framedrop_thresh(MemorySegment struct) {
        return struct.asSlice(framedrop_thresh$OFFSET, framedrop_thresh$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int framedrop_thresh[5]
     * }
     */
    public static void framedrop_thresh(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, framedrop_thresh$OFFSET, framedrop_thresh$LAYOUT.byteSize());
    }

    private static long[] framedrop_thresh$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int framedrop_thresh[5]
     * }
     */
    public static long[] framedrop_thresh$dimensions() {
        return framedrop_thresh$DIMS;
    }
    private static final VarHandle framedrop_thresh$ELEM_HANDLE = framedrop_thresh$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int framedrop_thresh[5]
     * }
     */
    public static int framedrop_thresh(MemorySegment struct, long index0) {
        return (int)framedrop_thresh$ELEM_HANDLE.get(struct, framedrop_thresh$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int framedrop_thresh[5]
     * }
     */
    public static void framedrop_thresh(MemorySegment struct, long index0, int fieldValue) {
        framedrop_thresh$ELEM_HANDLE.set(struct, framedrop_thresh$OFFSET, index0, fieldValue);
    }

    private static final OfInt framedrop_mode$LAYOUT = (OfInt)$LAYOUT.select(groupElement("framedrop_mode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SVC_LAYER_DROP_MODE framedrop_mode
     * }
     */
    public static final OfInt framedrop_mode$layout() {
        return framedrop_mode$LAYOUT;
    }

    private static final long framedrop_mode$OFFSET = $LAYOUT.byteOffset(groupElement("framedrop_mode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SVC_LAYER_DROP_MODE framedrop_mode
     * }
     */
    public static final long framedrop_mode$offset() {
        return framedrop_mode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SVC_LAYER_DROP_MODE framedrop_mode
     * }
     */
    public static int framedrop_mode(MemorySegment struct) {
        return struct.get(framedrop_mode$LAYOUT, framedrop_mode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SVC_LAYER_DROP_MODE framedrop_mode
     * }
     */
    public static void framedrop_mode(MemorySegment struct, int fieldValue) {
        struct.set(framedrop_mode$LAYOUT, framedrop_mode$OFFSET, fieldValue);
    }

    private static final OfInt max_consec_drop$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_consec_drop"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int max_consec_drop
     * }
     */
    public static final OfInt max_consec_drop$layout() {
        return max_consec_drop$LAYOUT;
    }

    private static final long max_consec_drop$OFFSET = $LAYOUT.byteOffset(groupElement("max_consec_drop"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int max_consec_drop
     * }
     */
    public static final long max_consec_drop$offset() {
        return max_consec_drop$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int max_consec_drop
     * }
     */
    public static int max_consec_drop(MemorySegment struct) {
        return struct.get(max_consec_drop$LAYOUT, max_consec_drop$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int max_consec_drop
     * }
     */
    public static void max_consec_drop(MemorySegment struct, int fieldValue) {
        struct.set(max_consec_drop$LAYOUT, max_consec_drop$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

