// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*vpx_codec_put_slice_cb_fn_t)(void *, const vpx_image_t *, const vpx_image_rect_t *, const vpx_image_rect_t *)
 * }
 */
public final class vpx_codec_put_slice_cb_fn_t {

    private vpx_codec_put_slice_cb_fn_t() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment user_priv, MemorySegment img, MemorySegment valid, MemorySegment update);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        VpxFFI.C_POINTER,
        VpxFFI.C_POINTER,
        VpxFFI.C_POINTER,
        VpxFFI.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = VpxFFI.upcallHandle(vpx_codec_put_slice_cb_fn_t.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(vpx_codec_put_slice_cb_fn_t.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment user_priv, MemorySegment img, MemorySegment valid, MemorySegment update) {
        try {
             DOWN$MH.invokeExact(funcPtr, user_priv, img, valid, update);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

