// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_codec_cx_pkt {
 *     enum vpx_codec_cx_pkt_kind kind;
 *     union {
 *         struct {
 *             void *buf;
 *             size_t sz;
 *             vpx_codec_pts_t pts;
 *             unsigned long duration;
 *             vpx_codec_frame_flags_t flags;
 *             int partition_id;
 *             unsigned int width[5];
 *             unsigned int height[5];
 *             uint8_t spatial_layer_encoded[5];
 *         } frame;
 *         vpx_fixed_buf_t twopass_stats;
 *         vpx_fixed_buf_t firstpass_mb_stats;
 *         struct vpx_psnr_pkt {
 *             unsigned int samples[4];
 *             uint64_t sse[4];
 *             double psnr[4];
 *             int spatial_layer_id;
 *         } psnr;
 *         vpx_fixed_buf_t raw;
 *         char pad[124];
 *     } data;
 * } vpx_codec_cx_pkt_t
 * }
 */
public class vpx_codec_cx_pkt_t extends vpx_codec_cx_pkt {

    vpx_codec_cx_pkt_t() {
        // Should not be called directly
    }
}

