// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_svc_ref_frame_config {
 *     int lst_fb_idx[5];
 *     int gld_fb_idx[5];
 *     int alt_fb_idx[5];
 *     int update_buffer_slot[5];
 *     int update_last[5];
 *     int update_golden[5];
 *     int update_alt_ref[5];
 *     int reference_last[5];
 *     int reference_golden[5];
 *     int reference_alt_ref[5];
 *     int64_t duration[5];
 * } vpx_svc_ref_frame_config_t
 * }
 */
public class vpx_svc_ref_frame_config_t extends vpx_svc_ref_frame_config {

    vpx_svc_ref_frame_config_t() {
        // Should not be called directly
    }
}

