// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vpx_svc_layer_id {
 *     int spatial_layer_id;
 *     int temporal_layer_id;
 *     int temporal_layer_id_per_spatial[5];
 * } vpx_svc_layer_id_t
 * }
 */
public class vpx_svc_layer_id_t extends vpx_svc_layer_id {

    vpx_svc_layer_id_t() {
        // Should not be called directly
    }
}

