// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_svc_ref_frame_config {
 *     int lst_fb_idx[5];
 *     int gld_fb_idx[5];
 *     int alt_fb_idx[5];
 *     int update_buffer_slot[5];
 *     int update_last[5];
 *     int update_golden[5];
 *     int update_alt_ref[5];
 *     int reference_last[5];
 *     int reference_golden[5];
 *     int reference_alt_ref[5];
 *     int64_t duration[5];
 * }
 * }
 */
public class vpx_svc_ref_frame_config {

    vpx_svc_ref_frame_config() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(5, VpxFFI.C_INT).withName("lst_fb_idx"),
        MemoryLayout.sequenceLayout(5, VpxFFI.C_INT).withName("gld_fb_idx"),
        MemoryLayout.sequenceLayout(5, VpxFFI.C_INT).withName("alt_fb_idx"),
        MemoryLayout.sequenceLayout(5, VpxFFI.C_INT).withName("update_buffer_slot"),
        MemoryLayout.sequenceLayout(5, VpxFFI.C_INT).withName("update_last"),
        MemoryLayout.sequenceLayout(5, VpxFFI.C_INT).withName("update_golden"),
        MemoryLayout.sequenceLayout(5, VpxFFI.C_INT).withName("update_alt_ref"),
        MemoryLayout.sequenceLayout(5, VpxFFI.C_INT).withName("reference_last"),
        MemoryLayout.sequenceLayout(5, VpxFFI.C_INT).withName("reference_golden"),
        MemoryLayout.sequenceLayout(5, VpxFFI.C_INT).withName("reference_alt_ref"),
        MemoryLayout.sequenceLayout(5, VpxFFI.C_LONG).withName("duration")
    ).withName("vpx_svc_ref_frame_config");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout lst_fb_idx$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("lst_fb_idx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int lst_fb_idx[5]
     * }
     */
    public static final SequenceLayout lst_fb_idx$layout() {
        return lst_fb_idx$LAYOUT;
    }

    private static final long lst_fb_idx$OFFSET = $LAYOUT.byteOffset(groupElement("lst_fb_idx"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int lst_fb_idx[5]
     * }
     */
    public static final long lst_fb_idx$offset() {
        return lst_fb_idx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int lst_fb_idx[5]
     * }
     */
    public static MemorySegment lst_fb_idx(MemorySegment struct) {
        return struct.asSlice(lst_fb_idx$OFFSET, lst_fb_idx$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int lst_fb_idx[5]
     * }
     */
    public static void lst_fb_idx(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, lst_fb_idx$OFFSET, lst_fb_idx$LAYOUT.byteSize());
    }

    private static long[] lst_fb_idx$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int lst_fb_idx[5]
     * }
     */
    public static long[] lst_fb_idx$dimensions() {
        return lst_fb_idx$DIMS;
    }
    private static final VarHandle lst_fb_idx$ELEM_HANDLE = lst_fb_idx$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int lst_fb_idx[5]
     * }
     */
    public static int lst_fb_idx(MemorySegment struct, long index0) {
        return (int)lst_fb_idx$ELEM_HANDLE.get(struct, lst_fb_idx$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int lst_fb_idx[5]
     * }
     */
    public static void lst_fb_idx(MemorySegment struct, long index0, int fieldValue) {
        lst_fb_idx$ELEM_HANDLE.set(struct, lst_fb_idx$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout gld_fb_idx$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("gld_fb_idx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int gld_fb_idx[5]
     * }
     */
    public static final SequenceLayout gld_fb_idx$layout() {
        return gld_fb_idx$LAYOUT;
    }

    private static final long gld_fb_idx$OFFSET = $LAYOUT.byteOffset(groupElement("gld_fb_idx"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int gld_fb_idx[5]
     * }
     */
    public static final long gld_fb_idx$offset() {
        return gld_fb_idx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int gld_fb_idx[5]
     * }
     */
    public static MemorySegment gld_fb_idx(MemorySegment struct) {
        return struct.asSlice(gld_fb_idx$OFFSET, gld_fb_idx$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int gld_fb_idx[5]
     * }
     */
    public static void gld_fb_idx(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, gld_fb_idx$OFFSET, gld_fb_idx$LAYOUT.byteSize());
    }

    private static long[] gld_fb_idx$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int gld_fb_idx[5]
     * }
     */
    public static long[] gld_fb_idx$dimensions() {
        return gld_fb_idx$DIMS;
    }
    private static final VarHandle gld_fb_idx$ELEM_HANDLE = gld_fb_idx$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int gld_fb_idx[5]
     * }
     */
    public static int gld_fb_idx(MemorySegment struct, long index0) {
        return (int)gld_fb_idx$ELEM_HANDLE.get(struct, gld_fb_idx$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int gld_fb_idx[5]
     * }
     */
    public static void gld_fb_idx(MemorySegment struct, long index0, int fieldValue) {
        gld_fb_idx$ELEM_HANDLE.set(struct, gld_fb_idx$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout alt_fb_idx$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("alt_fb_idx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int alt_fb_idx[5]
     * }
     */
    public static final SequenceLayout alt_fb_idx$layout() {
        return alt_fb_idx$LAYOUT;
    }

    private static final long alt_fb_idx$OFFSET = $LAYOUT.byteOffset(groupElement("alt_fb_idx"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int alt_fb_idx[5]
     * }
     */
    public static final long alt_fb_idx$offset() {
        return alt_fb_idx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int alt_fb_idx[5]
     * }
     */
    public static MemorySegment alt_fb_idx(MemorySegment struct) {
        return struct.asSlice(alt_fb_idx$OFFSET, alt_fb_idx$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int alt_fb_idx[5]
     * }
     */
    public static void alt_fb_idx(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, alt_fb_idx$OFFSET, alt_fb_idx$LAYOUT.byteSize());
    }

    private static long[] alt_fb_idx$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int alt_fb_idx[5]
     * }
     */
    public static long[] alt_fb_idx$dimensions() {
        return alt_fb_idx$DIMS;
    }
    private static final VarHandle alt_fb_idx$ELEM_HANDLE = alt_fb_idx$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int alt_fb_idx[5]
     * }
     */
    public static int alt_fb_idx(MemorySegment struct, long index0) {
        return (int)alt_fb_idx$ELEM_HANDLE.get(struct, alt_fb_idx$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int alt_fb_idx[5]
     * }
     */
    public static void alt_fb_idx(MemorySegment struct, long index0, int fieldValue) {
        alt_fb_idx$ELEM_HANDLE.set(struct, alt_fb_idx$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout update_buffer_slot$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("update_buffer_slot"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int update_buffer_slot[5]
     * }
     */
    public static final SequenceLayout update_buffer_slot$layout() {
        return update_buffer_slot$LAYOUT;
    }

    private static final long update_buffer_slot$OFFSET = $LAYOUT.byteOffset(groupElement("update_buffer_slot"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int update_buffer_slot[5]
     * }
     */
    public static final long update_buffer_slot$offset() {
        return update_buffer_slot$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int update_buffer_slot[5]
     * }
     */
    public static MemorySegment update_buffer_slot(MemorySegment struct) {
        return struct.asSlice(update_buffer_slot$OFFSET, update_buffer_slot$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int update_buffer_slot[5]
     * }
     */
    public static void update_buffer_slot(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, update_buffer_slot$OFFSET, update_buffer_slot$LAYOUT.byteSize());
    }

    private static long[] update_buffer_slot$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int update_buffer_slot[5]
     * }
     */
    public static long[] update_buffer_slot$dimensions() {
        return update_buffer_slot$DIMS;
    }
    private static final VarHandle update_buffer_slot$ELEM_HANDLE = update_buffer_slot$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int update_buffer_slot[5]
     * }
     */
    public static int update_buffer_slot(MemorySegment struct, long index0) {
        return (int)update_buffer_slot$ELEM_HANDLE.get(struct, update_buffer_slot$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int update_buffer_slot[5]
     * }
     */
    public static void update_buffer_slot(MemorySegment struct, long index0, int fieldValue) {
        update_buffer_slot$ELEM_HANDLE.set(struct, update_buffer_slot$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout update_last$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("update_last"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int update_last[5]
     * }
     */
    public static final SequenceLayout update_last$layout() {
        return update_last$LAYOUT;
    }

    private static final long update_last$OFFSET = $LAYOUT.byteOffset(groupElement("update_last"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int update_last[5]
     * }
     */
    public static final long update_last$offset() {
        return update_last$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int update_last[5]
     * }
     */
    public static MemorySegment update_last(MemorySegment struct) {
        return struct.asSlice(update_last$OFFSET, update_last$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int update_last[5]
     * }
     */
    public static void update_last(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, update_last$OFFSET, update_last$LAYOUT.byteSize());
    }

    private static long[] update_last$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int update_last[5]
     * }
     */
    public static long[] update_last$dimensions() {
        return update_last$DIMS;
    }
    private static final VarHandle update_last$ELEM_HANDLE = update_last$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int update_last[5]
     * }
     */
    public static int update_last(MemorySegment struct, long index0) {
        return (int)update_last$ELEM_HANDLE.get(struct, update_last$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int update_last[5]
     * }
     */
    public static void update_last(MemorySegment struct, long index0, int fieldValue) {
        update_last$ELEM_HANDLE.set(struct, update_last$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout update_golden$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("update_golden"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int update_golden[5]
     * }
     */
    public static final SequenceLayout update_golden$layout() {
        return update_golden$LAYOUT;
    }

    private static final long update_golden$OFFSET = $LAYOUT.byteOffset(groupElement("update_golden"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int update_golden[5]
     * }
     */
    public static final long update_golden$offset() {
        return update_golden$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int update_golden[5]
     * }
     */
    public static MemorySegment update_golden(MemorySegment struct) {
        return struct.asSlice(update_golden$OFFSET, update_golden$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int update_golden[5]
     * }
     */
    public static void update_golden(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, update_golden$OFFSET, update_golden$LAYOUT.byteSize());
    }

    private static long[] update_golden$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int update_golden[5]
     * }
     */
    public static long[] update_golden$dimensions() {
        return update_golden$DIMS;
    }
    private static final VarHandle update_golden$ELEM_HANDLE = update_golden$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int update_golden[5]
     * }
     */
    public static int update_golden(MemorySegment struct, long index0) {
        return (int)update_golden$ELEM_HANDLE.get(struct, update_golden$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int update_golden[5]
     * }
     */
    public static void update_golden(MemorySegment struct, long index0, int fieldValue) {
        update_golden$ELEM_HANDLE.set(struct, update_golden$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout update_alt_ref$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("update_alt_ref"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int update_alt_ref[5]
     * }
     */
    public static final SequenceLayout update_alt_ref$layout() {
        return update_alt_ref$LAYOUT;
    }

    private static final long update_alt_ref$OFFSET = $LAYOUT.byteOffset(groupElement("update_alt_ref"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int update_alt_ref[5]
     * }
     */
    public static final long update_alt_ref$offset() {
        return update_alt_ref$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int update_alt_ref[5]
     * }
     */
    public static MemorySegment update_alt_ref(MemorySegment struct) {
        return struct.asSlice(update_alt_ref$OFFSET, update_alt_ref$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int update_alt_ref[5]
     * }
     */
    public static void update_alt_ref(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, update_alt_ref$OFFSET, update_alt_ref$LAYOUT.byteSize());
    }

    private static long[] update_alt_ref$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int update_alt_ref[5]
     * }
     */
    public static long[] update_alt_ref$dimensions() {
        return update_alt_ref$DIMS;
    }
    private static final VarHandle update_alt_ref$ELEM_HANDLE = update_alt_ref$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int update_alt_ref[5]
     * }
     */
    public static int update_alt_ref(MemorySegment struct, long index0) {
        return (int)update_alt_ref$ELEM_HANDLE.get(struct, update_alt_ref$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int update_alt_ref[5]
     * }
     */
    public static void update_alt_ref(MemorySegment struct, long index0, int fieldValue) {
        update_alt_ref$ELEM_HANDLE.set(struct, update_alt_ref$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout reference_last$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("reference_last"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int reference_last[5]
     * }
     */
    public static final SequenceLayout reference_last$layout() {
        return reference_last$LAYOUT;
    }

    private static final long reference_last$OFFSET = $LAYOUT.byteOffset(groupElement("reference_last"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int reference_last[5]
     * }
     */
    public static final long reference_last$offset() {
        return reference_last$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int reference_last[5]
     * }
     */
    public static MemorySegment reference_last(MemorySegment struct) {
        return struct.asSlice(reference_last$OFFSET, reference_last$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int reference_last[5]
     * }
     */
    public static void reference_last(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, reference_last$OFFSET, reference_last$LAYOUT.byteSize());
    }

    private static long[] reference_last$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int reference_last[5]
     * }
     */
    public static long[] reference_last$dimensions() {
        return reference_last$DIMS;
    }
    private static final VarHandle reference_last$ELEM_HANDLE = reference_last$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int reference_last[5]
     * }
     */
    public static int reference_last(MemorySegment struct, long index0) {
        return (int)reference_last$ELEM_HANDLE.get(struct, reference_last$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int reference_last[5]
     * }
     */
    public static void reference_last(MemorySegment struct, long index0, int fieldValue) {
        reference_last$ELEM_HANDLE.set(struct, reference_last$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout reference_golden$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("reference_golden"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int reference_golden[5]
     * }
     */
    public static final SequenceLayout reference_golden$layout() {
        return reference_golden$LAYOUT;
    }

    private static final long reference_golden$OFFSET = $LAYOUT.byteOffset(groupElement("reference_golden"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int reference_golden[5]
     * }
     */
    public static final long reference_golden$offset() {
        return reference_golden$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int reference_golden[5]
     * }
     */
    public static MemorySegment reference_golden(MemorySegment struct) {
        return struct.asSlice(reference_golden$OFFSET, reference_golden$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int reference_golden[5]
     * }
     */
    public static void reference_golden(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, reference_golden$OFFSET, reference_golden$LAYOUT.byteSize());
    }

    private static long[] reference_golden$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int reference_golden[5]
     * }
     */
    public static long[] reference_golden$dimensions() {
        return reference_golden$DIMS;
    }
    private static final VarHandle reference_golden$ELEM_HANDLE = reference_golden$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int reference_golden[5]
     * }
     */
    public static int reference_golden(MemorySegment struct, long index0) {
        return (int)reference_golden$ELEM_HANDLE.get(struct, reference_golden$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int reference_golden[5]
     * }
     */
    public static void reference_golden(MemorySegment struct, long index0, int fieldValue) {
        reference_golden$ELEM_HANDLE.set(struct, reference_golden$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout reference_alt_ref$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("reference_alt_ref"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int reference_alt_ref[5]
     * }
     */
    public static final SequenceLayout reference_alt_ref$layout() {
        return reference_alt_ref$LAYOUT;
    }

    private static final long reference_alt_ref$OFFSET = $LAYOUT.byteOffset(groupElement("reference_alt_ref"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int reference_alt_ref[5]
     * }
     */
    public static final long reference_alt_ref$offset() {
        return reference_alt_ref$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int reference_alt_ref[5]
     * }
     */
    public static MemorySegment reference_alt_ref(MemorySegment struct) {
        return struct.asSlice(reference_alt_ref$OFFSET, reference_alt_ref$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int reference_alt_ref[5]
     * }
     */
    public static void reference_alt_ref(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, reference_alt_ref$OFFSET, reference_alt_ref$LAYOUT.byteSize());
    }

    private static long[] reference_alt_ref$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int reference_alt_ref[5]
     * }
     */
    public static long[] reference_alt_ref$dimensions() {
        return reference_alt_ref$DIMS;
    }
    private static final VarHandle reference_alt_ref$ELEM_HANDLE = reference_alt_ref$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int reference_alt_ref[5]
     * }
     */
    public static int reference_alt_ref(MemorySegment struct, long index0) {
        return (int)reference_alt_ref$ELEM_HANDLE.get(struct, reference_alt_ref$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int reference_alt_ref[5]
     * }
     */
    public static void reference_alt_ref(MemorySegment struct, long index0, int fieldValue) {
        reference_alt_ref$ELEM_HANDLE.set(struct, reference_alt_ref$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout duration$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("duration"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t duration[5]
     * }
     */
    public static final SequenceLayout duration$layout() {
        return duration$LAYOUT;
    }

    private static final long duration$OFFSET = $LAYOUT.byteOffset(groupElement("duration"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t duration[5]
     * }
     */
    public static final long duration$offset() {
        return duration$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t duration[5]
     * }
     */
    public static MemorySegment duration(MemorySegment struct) {
        return struct.asSlice(duration$OFFSET, duration$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t duration[5]
     * }
     */
    public static void duration(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, duration$OFFSET, duration$LAYOUT.byteSize());
    }

    private static long[] duration$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int64_t duration[5]
     * }
     */
    public static long[] duration$dimensions() {
        return duration$DIMS;
    }
    private static final VarHandle duration$ELEM_HANDLE = duration$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int64_t duration[5]
     * }
     */
    public static long duration(MemorySegment struct, long index0) {
        return (long)duration$ELEM_HANDLE.get(struct, duration$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int64_t duration[5]
     * }
     */
    public static void duration(MemorySegment struct, long index0, long fieldValue) {
        duration$ELEM_HANDLE.set(struct, duration$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

