// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct VpxTplFrameStats {
 *     int frame_width;
 *     int frame_height;
 *     int num_blocks;
 *     VpxTplBlockStats *block_stats_list;
 * }
 * }
 */
public class VpxTplFrameStats {

    VpxTplFrameStats() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_INT.withName("frame_width"),
        VpxFFI.C_INT.withName("frame_height"),
        VpxFFI.C_INT.withName("num_blocks"),
        MemoryLayout.paddingLayout(4),
        VpxFFI.C_POINTER.withName("block_stats_list")
    ).withName("VpxTplFrameStats");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt frame_width$LAYOUT = (OfInt)$LAYOUT.select(groupElement("frame_width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int frame_width
     * }
     */
    public static final OfInt frame_width$layout() {
        return frame_width$LAYOUT;
    }

    private static final long frame_width$OFFSET = $LAYOUT.byteOffset(groupElement("frame_width"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int frame_width
     * }
     */
    public static final long frame_width$offset() {
        return frame_width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int frame_width
     * }
     */
    public static int frame_width(MemorySegment struct) {
        return struct.get(frame_width$LAYOUT, frame_width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int frame_width
     * }
     */
    public static void frame_width(MemorySegment struct, int fieldValue) {
        struct.set(frame_width$LAYOUT, frame_width$OFFSET, fieldValue);
    }

    private static final OfInt frame_height$LAYOUT = (OfInt)$LAYOUT.select(groupElement("frame_height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int frame_height
     * }
     */
    public static final OfInt frame_height$layout() {
        return frame_height$LAYOUT;
    }

    private static final long frame_height$OFFSET = $LAYOUT.byteOffset(groupElement("frame_height"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int frame_height
     * }
     */
    public static final long frame_height$offset() {
        return frame_height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int frame_height
     * }
     */
    public static int frame_height(MemorySegment struct) {
        return struct.get(frame_height$LAYOUT, frame_height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int frame_height
     * }
     */
    public static void frame_height(MemorySegment struct, int fieldValue) {
        struct.set(frame_height$LAYOUT, frame_height$OFFSET, fieldValue);
    }

    private static final OfInt num_blocks$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_blocks"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int num_blocks
     * }
     */
    public static final OfInt num_blocks$layout() {
        return num_blocks$LAYOUT;
    }

    private static final long num_blocks$OFFSET = $LAYOUT.byteOffset(groupElement("num_blocks"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int num_blocks
     * }
     */
    public static final long num_blocks$offset() {
        return num_blocks$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int num_blocks
     * }
     */
    public static int num_blocks(MemorySegment struct) {
        return struct.get(num_blocks$LAYOUT, num_blocks$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int num_blocks
     * }
     */
    public static void num_blocks(MemorySegment struct, int fieldValue) {
        struct.set(num_blocks$LAYOUT, num_blocks$OFFSET, fieldValue);
    }

    private static final AddressLayout block_stats_list$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("block_stats_list"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VpxTplBlockStats *block_stats_list
     * }
     */
    public static final AddressLayout block_stats_list$layout() {
        return block_stats_list$LAYOUT;
    }

    private static final long block_stats_list$OFFSET = $LAYOUT.byteOffset(groupElement("block_stats_list"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VpxTplBlockStats *block_stats_list
     * }
     */
    public static final long block_stats_list$offset() {
        return block_stats_list$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VpxTplBlockStats *block_stats_list
     * }
     */
    public static MemorySegment block_stats_list(MemorySegment struct) {
        return struct.get(block_stats_list$LAYOUT, block_stats_list$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VpxTplBlockStats *block_stats_list
     * }
     */
    public static void block_stats_list(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(block_stats_list$LAYOUT, block_stats_list$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

