// Generated by jextract

package org.seuffert.panvpx.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct VpxTplBlockStats {
 *     int16_t row;
 *     int16_t col;
 *     int64_t intra_cost;
 *     int64_t inter_cost;
 *     int16_t mv_r;
 *     int16_t mv_c;
 *     int64_t srcrf_rate;
 *     int64_t srcrf_dist;
 *     int64_t pred_error;
 *     int64_t inter_pred_err;
 *     int64_t intra_pred_err;
 *     int ref_frame_index;
 * }
 * }
 */
public class VpxTplBlockStats {

    VpxTplBlockStats() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        VpxFFI.C_SHORT.withName("row"),
        VpxFFI.C_SHORT.withName("col"),
        MemoryLayout.paddingLayout(4),
        VpxFFI.C_LONG.withName("intra_cost"),
        VpxFFI.C_LONG.withName("inter_cost"),
        VpxFFI.C_SHORT.withName("mv_r"),
        VpxFFI.C_SHORT.withName("mv_c"),
        MemoryLayout.paddingLayout(4),
        VpxFFI.C_LONG.withName("srcrf_rate"),
        VpxFFI.C_LONG.withName("srcrf_dist"),
        VpxFFI.C_LONG.withName("pred_error"),
        VpxFFI.C_LONG.withName("inter_pred_err"),
        VpxFFI.C_LONG.withName("intra_pred_err"),
        VpxFFI.C_INT.withName("ref_frame_index"),
        MemoryLayout.paddingLayout(4)
    ).withName("VpxTplBlockStats");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfShort row$LAYOUT = (OfShort)$LAYOUT.select(groupElement("row"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int16_t row
     * }
     */
    public static final OfShort row$layout() {
        return row$LAYOUT;
    }

    private static final long row$OFFSET = $LAYOUT.byteOffset(groupElement("row"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int16_t row
     * }
     */
    public static final long row$offset() {
        return row$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int16_t row
     * }
     */
    public static short row(MemorySegment struct) {
        return struct.get(row$LAYOUT, row$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int16_t row
     * }
     */
    public static void row(MemorySegment struct, short fieldValue) {
        struct.set(row$LAYOUT, row$OFFSET, fieldValue);
    }

    private static final OfShort col$LAYOUT = (OfShort)$LAYOUT.select(groupElement("col"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int16_t col
     * }
     */
    public static final OfShort col$layout() {
        return col$LAYOUT;
    }

    private static final long col$OFFSET = $LAYOUT.byteOffset(groupElement("col"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int16_t col
     * }
     */
    public static final long col$offset() {
        return col$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int16_t col
     * }
     */
    public static short col(MemorySegment struct) {
        return struct.get(col$LAYOUT, col$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int16_t col
     * }
     */
    public static void col(MemorySegment struct, short fieldValue) {
        struct.set(col$LAYOUT, col$OFFSET, fieldValue);
    }

    private static final OfLong intra_cost$LAYOUT = (OfLong)$LAYOUT.select(groupElement("intra_cost"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t intra_cost
     * }
     */
    public static final OfLong intra_cost$layout() {
        return intra_cost$LAYOUT;
    }

    private static final long intra_cost$OFFSET = $LAYOUT.byteOffset(groupElement("intra_cost"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t intra_cost
     * }
     */
    public static final long intra_cost$offset() {
        return intra_cost$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t intra_cost
     * }
     */
    public static long intra_cost(MemorySegment struct) {
        return struct.get(intra_cost$LAYOUT, intra_cost$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t intra_cost
     * }
     */
    public static void intra_cost(MemorySegment struct, long fieldValue) {
        struct.set(intra_cost$LAYOUT, intra_cost$OFFSET, fieldValue);
    }

    private static final OfLong inter_cost$LAYOUT = (OfLong)$LAYOUT.select(groupElement("inter_cost"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t inter_cost
     * }
     */
    public static final OfLong inter_cost$layout() {
        return inter_cost$LAYOUT;
    }

    private static final long inter_cost$OFFSET = $LAYOUT.byteOffset(groupElement("inter_cost"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t inter_cost
     * }
     */
    public static final long inter_cost$offset() {
        return inter_cost$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t inter_cost
     * }
     */
    public static long inter_cost(MemorySegment struct) {
        return struct.get(inter_cost$LAYOUT, inter_cost$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t inter_cost
     * }
     */
    public static void inter_cost(MemorySegment struct, long fieldValue) {
        struct.set(inter_cost$LAYOUT, inter_cost$OFFSET, fieldValue);
    }

    private static final OfShort mv_r$LAYOUT = (OfShort)$LAYOUT.select(groupElement("mv_r"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int16_t mv_r
     * }
     */
    public static final OfShort mv_r$layout() {
        return mv_r$LAYOUT;
    }

    private static final long mv_r$OFFSET = $LAYOUT.byteOffset(groupElement("mv_r"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int16_t mv_r
     * }
     */
    public static final long mv_r$offset() {
        return mv_r$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int16_t mv_r
     * }
     */
    public static short mv_r(MemorySegment struct) {
        return struct.get(mv_r$LAYOUT, mv_r$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int16_t mv_r
     * }
     */
    public static void mv_r(MemorySegment struct, short fieldValue) {
        struct.set(mv_r$LAYOUT, mv_r$OFFSET, fieldValue);
    }

    private static final OfShort mv_c$LAYOUT = (OfShort)$LAYOUT.select(groupElement("mv_c"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int16_t mv_c
     * }
     */
    public static final OfShort mv_c$layout() {
        return mv_c$LAYOUT;
    }

    private static final long mv_c$OFFSET = $LAYOUT.byteOffset(groupElement("mv_c"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int16_t mv_c
     * }
     */
    public static final long mv_c$offset() {
        return mv_c$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int16_t mv_c
     * }
     */
    public static short mv_c(MemorySegment struct) {
        return struct.get(mv_c$LAYOUT, mv_c$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int16_t mv_c
     * }
     */
    public static void mv_c(MemorySegment struct, short fieldValue) {
        struct.set(mv_c$LAYOUT, mv_c$OFFSET, fieldValue);
    }

    private static final OfLong srcrf_rate$LAYOUT = (OfLong)$LAYOUT.select(groupElement("srcrf_rate"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t srcrf_rate
     * }
     */
    public static final OfLong srcrf_rate$layout() {
        return srcrf_rate$LAYOUT;
    }

    private static final long srcrf_rate$OFFSET = $LAYOUT.byteOffset(groupElement("srcrf_rate"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t srcrf_rate
     * }
     */
    public static final long srcrf_rate$offset() {
        return srcrf_rate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t srcrf_rate
     * }
     */
    public static long srcrf_rate(MemorySegment struct) {
        return struct.get(srcrf_rate$LAYOUT, srcrf_rate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t srcrf_rate
     * }
     */
    public static void srcrf_rate(MemorySegment struct, long fieldValue) {
        struct.set(srcrf_rate$LAYOUT, srcrf_rate$OFFSET, fieldValue);
    }

    private static final OfLong srcrf_dist$LAYOUT = (OfLong)$LAYOUT.select(groupElement("srcrf_dist"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t srcrf_dist
     * }
     */
    public static final OfLong srcrf_dist$layout() {
        return srcrf_dist$LAYOUT;
    }

    private static final long srcrf_dist$OFFSET = $LAYOUT.byteOffset(groupElement("srcrf_dist"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t srcrf_dist
     * }
     */
    public static final long srcrf_dist$offset() {
        return srcrf_dist$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t srcrf_dist
     * }
     */
    public static long srcrf_dist(MemorySegment struct) {
        return struct.get(srcrf_dist$LAYOUT, srcrf_dist$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t srcrf_dist
     * }
     */
    public static void srcrf_dist(MemorySegment struct, long fieldValue) {
        struct.set(srcrf_dist$LAYOUT, srcrf_dist$OFFSET, fieldValue);
    }

    private static final OfLong pred_error$LAYOUT = (OfLong)$LAYOUT.select(groupElement("pred_error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t pred_error
     * }
     */
    public static final OfLong pred_error$layout() {
        return pred_error$LAYOUT;
    }

    private static final long pred_error$OFFSET = $LAYOUT.byteOffset(groupElement("pred_error"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t pred_error
     * }
     */
    public static final long pred_error$offset() {
        return pred_error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t pred_error
     * }
     */
    public static long pred_error(MemorySegment struct) {
        return struct.get(pred_error$LAYOUT, pred_error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t pred_error
     * }
     */
    public static void pred_error(MemorySegment struct, long fieldValue) {
        struct.set(pred_error$LAYOUT, pred_error$OFFSET, fieldValue);
    }

    private static final OfLong inter_pred_err$LAYOUT = (OfLong)$LAYOUT.select(groupElement("inter_pred_err"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t inter_pred_err
     * }
     */
    public static final OfLong inter_pred_err$layout() {
        return inter_pred_err$LAYOUT;
    }

    private static final long inter_pred_err$OFFSET = $LAYOUT.byteOffset(groupElement("inter_pred_err"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t inter_pred_err
     * }
     */
    public static final long inter_pred_err$offset() {
        return inter_pred_err$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t inter_pred_err
     * }
     */
    public static long inter_pred_err(MemorySegment struct) {
        return struct.get(inter_pred_err$LAYOUT, inter_pred_err$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t inter_pred_err
     * }
     */
    public static void inter_pred_err(MemorySegment struct, long fieldValue) {
        struct.set(inter_pred_err$LAYOUT, inter_pred_err$OFFSET, fieldValue);
    }

    private static final OfLong intra_pred_err$LAYOUT = (OfLong)$LAYOUT.select(groupElement("intra_pred_err"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t intra_pred_err
     * }
     */
    public static final OfLong intra_pred_err$layout() {
        return intra_pred_err$LAYOUT;
    }

    private static final long intra_pred_err$OFFSET = $LAYOUT.byteOffset(groupElement("intra_pred_err"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t intra_pred_err
     * }
     */
    public static final long intra_pred_err$offset() {
        return intra_pred_err$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t intra_pred_err
     * }
     */
    public static long intra_pred_err(MemorySegment struct) {
        return struct.get(intra_pred_err$LAYOUT, intra_pred_err$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t intra_pred_err
     * }
     */
    public static void intra_pred_err(MemorySegment struct, long fieldValue) {
        struct.set(intra_pred_err$LAYOUT, intra_pred_err$OFFSET, fieldValue);
    }

    private static final OfInt ref_frame_index$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ref_frame_index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int ref_frame_index
     * }
     */
    public static final OfInt ref_frame_index$layout() {
        return ref_frame_index$LAYOUT;
    }

    private static final long ref_frame_index$OFFSET = $LAYOUT.byteOffset(groupElement("ref_frame_index"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int ref_frame_index
     * }
     */
    public static final long ref_frame_index$offset() {
        return ref_frame_index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int ref_frame_index
     * }
     */
    public static int ref_frame_index(MemorySegment struct) {
        return struct.get(ref_frame_index$LAYOUT, ref_frame_index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int ref_frame_index
     * }
     */
    public static void ref_frame_index(MemorySegment struct, int fieldValue) {
        struct.set(ref_frame_index$LAYOUT, ref_frame_index$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

